### ISSUE TITLE
Shifted vegetation & critters in Wall Village

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#10]
Some vegetation here is shifted by 8 trixels below.

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/Wall_Village.png

**Comment by renaudbedard** [comment]
Took a bunch of number fiddling, but it's all good now! Finally. :)
![image](https://cloud.githubusercontent.com/assets/251134/11648003/f433b35e-9d3c-11e5-8609-3b6c4bd72ee7.png)

**Comment by Gimlao** [comment]
I'm seeing something else : animals are also shifted down.

I can see rabbits and snails inside the floor : 
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/Wall_Village_Animals1.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/Wall_Village_Animals2.png

**Comment by renaudbedard** [comment]
?!
I hope this was always there? I don't see how last night's build would introduce that issue.

**Comment by renaudbedard** [comment]
Fixed the NPCs, and also noticed that the base of the flat statues was also embedded in the ground, so pushed them up as well. All good now! RIGHT??
