### ISSUE TITLE
Crash when entering the Fork room under the Ligthhouse

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#100]
» [Log](http://pastebin.com/ztc5Lyex)

**Comment by flibitijibibo** [comment]
I actually got this same error in another room! I _think_ I've fixed this, but all I did was add a lock to the offending object. Let me know if you hit this again, but I do believe this is fixed in threaded mode.

**Comment by flibitijibibo** [comment]
I did a bunch more things to make the level manager WAY more paranoid about editing that object, so the next update should not have this.
