### ISSUE TITLE
DOT jitters/glitches in the Villageville 3D intro cutscene

### ISSUE THREAD

**Issue by renaudbedard** [renaudbedard/fez-1.12-issues#102]
This is a consequence of the movement interpolation code I added a while back, it's known but not yet addressed :)

**Comment by renaudbedard** [comment]
Fixed, but in kind of a cheap way that makes everything feel real nice... all the update logic has been moved to the draw callback. So everything happens per-frame, even sound triggers, and some semi-risky stuff like re-culls. So far I haven't noticed any problem, and all the interpolation is now framerate independant and looks great on >60hz, so I think it's a winner.

Let me know if DOT acts weirdly in the game though!

**Comment by flibitijibibo** [comment]
Certain cutscenes got borked by the first fix, we've fixed the fix for the next update.
