### ISSUE TITLE
WorldMap textures vertically stretched in taller resolutions

### ISSUE THREAD

**Issue by flibitijibibo** [renaudbedard/fez-1.12-issues#104]
Can't quite make heads or tails of this one... it's only vertically ~~and it's only in pixel-perfect view~~:

![screenshot from 2016-06-16 11-38-50](https://cloud.githubusercontent.com/assets/1396814/16122888/f1ce343e-33b6-11e6-8398-b863abc2e41f.png)

It appears to just be the texcoords, but I dunno why they would change at all ~~(specifically in this mode)~~.

**Comment by flibitijibibo** [comment]
Just messed with a bunch of resolutions to be sure, it's actually based on viewport height and aspect ratio in general. It just happens to be that 16:9 1920x1080 also stretches vertically in pixel-perfect, but not full aspect. 1920x1200 shows this off _just slightly_, so that may be how I missed it in debug sessions.

**Comment by flibitijibibo** [comment]
I opened this issue thinking it'd be some really weird thing that'd take a while, but it turns out the Node effect just needed to calculate VScale in addition to HScale. WHO WOULD HAVE THOUGHT

With sincerest apologies to everyone who subs to this GitHub repo~

**Comment by renaudbedard** [comment]
:+1:
