### ISSUE TITLE
Game crashes when alt-tabbing from full screen mode

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#105]
Title is self-explaining I guess.
I'm on Windows 10.

**Comment by flibitijibibo** [comment]
Any logs...?

**Comment by Gyoo** [comment]
Sorry, I forget the most important thing

[[2016-06-19] Debug Log #2.txt](https://github.com/renaudbedard/fez-1.12-issues/files/322363/2016-06-19.Debug.Log.2.txt)

**Comment by flibitijibibo** [comment]
Ah, this is apparently a GL bug related to your driver. This only happens in debug mode and it happens on wglSwapBuffers once on fullscreen refocus, the fna-unstable branch will not emit this error. Best I can say is "thanks Windows 10..."

I do need to add the FNA logs to the FEZ log though, I'll roll that in tomorrow.
