### ISSUE TITLE
"Preserve aspect ratio" setting

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#108]
I think that "Preserve aspect ratio" setting will be useful. For example, I have a TV with 1920×1080 resolution and a display with 1920×1200 resolution. I'm switching between them sometimes :)

I can set 1920×1080 in the settings to work ok on both my displays. But now proportions of the image will be distorted on my display with 1920×1200 native resolution. It is not very nice.

I think that it is better to preserve aspect ratio by default. Black bars is much better than distorted proportions.

FNA uses SDL2.  It seems that SDL2 have to preserve aspect ratio by default, as [this document](https://wiki.libsdl.org/MigrationGuide) says:

> Note that 640x480 and 1920x1200 aren't the same aspect ratio: SDL takes care of that, too, scaling as much as possible and letterboxing the difference.

So, I think that it is not so hard to add such setting. What do you think?

**Comment by vrubleg** [comment]
FNA uses SDL2.  It seems that SDL2 have to preserve aspect ratio by default, as [this document](https://wiki.libsdl.org/MigrationGuide) says:

> Note that 640x480 and 1920x1200 aren't the same aspect ratio: SDL takes care of that, too, scaling as much as possible and letterboxing the difference.

So, I think that it is not so hard to add such setting. What do you think?

**Comment by flibitijibibo** [comment]
As the developer of FNA and a contributor to SDL2 I can clarify what's actually happening...

The way we're doing display settings in FEZ is very relaxed, deliberately. We get display settings from the GraphicsAdapter, per XNA4 spec...

https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.graphicsadapter.supporteddisplaymodes.aspx

In theory we could check the settings width/height values and force them into the supported modes, but this restricts the flexibility pretty heavily and for folks like myself who have limited display options provided by the X server on Linux, it becomes painful to run at modes like 1280x800 on a 16:10 display even when it obviously fits properly. Additionally, it ruins the ability to do arbitrary downsampling for people who have the hardware for it (i.e. turn on fullscreen, set width/height to 10240x5760, it'll work if you have a lot of VRAM).

So, in this case, the settings we have work for the original display, but when you move over to the new display, the old settings are preserved by FNA running a faux-backbuffer to render at 1920x1080 and blit to 1920x1200, the window resolution being dictated by SDL_WINDOW_FULLSCREEN_DESKTOP.

The best solution for frequent display swapping is to simply set the resolution you want in the video settings once you've moved to the new display, or set it in the config file between runs.

**Comment by vrubleg** [comment]
I'm not switching between displays during gameplay. For example, I have these settings:

```
    useCurrentMode false
    screenMode "Fullscreen"
    scaleMode "FullAspect"
    width 1920
    height 1080
```

I'm running the game on my main display with 1920×1200 resolution, and as the result I have stretched image, but I think that it is better to have letterboxing here. Maybe it is better to add additional screenMode (Fullscreen / FullscreenStretched), so if someone likes stretched image, it will be possible to enable it.

BTW, I see the useCurrentMode setting in the Settings file. It seems that when this setting is enabled, resolution setting is ignored (but it is not disabled in the interface, you can change it without any result, which is a bit confusing). I propose to set useCurrentMode to true automatically if user chooses (in the settings) the same resolution as the current system resolution. So when user will run the game on other display with different current resolution, the game will use this resolution automatically. But when user sets any other resolution in the settings, useCurrentMode have to be set to false automatically. It will be very useful for users who use different displays.

**Comment by flibitijibibo** [comment]
The problem is that the game has no concept of letterboxing at that point - the game thinks it's running in 1920x1080, we're just doing some work in FNA to prevent it from crashing by never touching the display mode (a particularly big no-no for Big Picture environments). This is standard behavior for SDL_WINDOW_FULLSCREEN_DESKTOP applications that use an FBO to simulate non-native display sizes.

I believe that CurrentMode setting is an old thing from when the Windows version used OpenTK and needed a way to fix its fullscreen mode (a LOT of hacks got cut out, and it seems that got left in)... that's probably your best bet if you don't want to open the video settings menu, but aside from that, the video settings are going to stay as-is. I'll at least disable the resolution options for UseCurrentMode = true, so that option gets some more use out of it.

**Comment by vrubleg** [comment]
> The problem is that the game has no concept of letterboxing at that point - the game thinks it's running in 1920x1080

I understand it. But I thought that SDL2 itself can keep aspect ratio and add letterboxing if "simulated" resolution has different aspect ratio in comparison to the real aspect ratio of the current system resolution.

It is very strange that SDL2 allows to "simulate" any resolutions, but doesn't allow to preserve aspect ratio. SDL2 knows a real resolution that is used for displaying, so SDL2 could add letterboxing for avoiding distortion of proportions.  Shame on SDL2 if it can't do such simple thing.

Fez is a game about squares, not about elongated rectangles.

UPD. I'm not a native English speaker. Maybe my description of the problem is a little bit confusing. Sorry for it in this case.

Just for example.
How 1920×1080 looks on my display with native resolution 1920×1200:
http://veg.by/z/2016-07-12-12-04-48-1f0a8359.png (wrong proportions).
It have to look like this:
http://veg.by/z/2016-07-12-12-05-06-c49b347b.png (right proportions, letterboxing).

**Comment by flibitijibibo** [comment]
The aspect ratio preservation is from SDL_RenderSetLogicalSize, which is more about the GL viewport than the window (and is only used when not explicitly managing your own GL context). I would have a look at that as well as SDL_SetWindowFullscreen.

**Comment by vrubleg** [comment]
Every time when I'm switching between v1.11 and v1.12 the game resets resolution to the 1280×720. As I understand, it is the default resolution. But it is 16:9. If a user has non-16:9 display (like me), he will see the image with distorted proportions. Just imagine how it will look on a 1280×1024 display :) The first impression is very important.

Possible solutions:
1. Preserve aspect ratio (add letterboxing if game resolution aspect ratio is different from the native resolution aspect ratio).
2. Choose default resolution with aspect ratio similar to the native resolution aspect ratio, at least if it is available (usually there are several 1280×XXX resolutions with all popular aspect ratios).

Sorry if I'm annoying with this issue =)

**Comment by renaudbedard** [comment]
I think the game should attempt to start at the desktop resolution by default, not 720p. We had issues in versions before 1.11 where the game would start at unsupported display resolutions and resulting in a black screen... but I think SDL will report the native/desktop resolution accurately and we could use that as the "first run" fullscreen resolution.
Thoughts, @flibitijibibo?

**Comment by flibitijibibo** [comment]
Yeah, we can just use the default desktop res. I'll commit that once I've finished uploading this other game...

**Comment by flibitijibibo** [comment]
The next update should handle this, though I'd like for this to be tested on Windows so we know for sure it's fixed.

**Comment by renaudbedard** [comment]
![image](https://cloud.githubusercontent.com/assets/251134/17009568/36d218a6-4eca-11e6-836b-422c08264d56.png)

**Comment by vrubleg** [comment]
It seems that it is implemented:

> 05/08 - Added black bars in fullscreen for resolutions that don't match the native aspect ratio of the display

Unfortunately, it is buggy when you're changing resolution in settings. As the result there may be the black bars when native 16:10 resolution is chosen (just after 16:9). Or there may be horizontal AND vertical black bars when 16:9 resolution is changed to 4:3 resolution on 16:10 display. Just try to change resolution in settings before gameplay and during gameplay, choose resolutions with different aspect ratios every time. It seems that it is easy to reproduce.

**Comment by flibitijibibo** [comment]
Got it, the cause is likely us not setting the bar dimensions throughout every type of boxing mode. Just need to set some variables to 0 at the right time... let's check this one more time in the next build.
