### ISSUE TITLE
Broken background animation when switching between 2D and 3D

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#109]
Look at these things while switching between 2D and 3D:
http://veg.by/z/2016-07-12-08-38-24-618cf24d.png
http://veg.by/z/2016-07-12-08-37-38-817409b7.png
They "jump" at the end of the transition animation.
Fez v1.11 doesn't have such glitch.

**Comment by flibitijibibo** [comment]
This is a regression from some of the 17ms work, Renaud will probably have to deal with this one...

**Comment by renaudbedard** [comment]
Will take a look tonite!

**Comment by renaudbedard** [comment]
Will be fixed in next update, thanks!
