### ISSUE TITLE
"mojoshader.dll" Crash / vcredist 2015

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#11]
The game now needs vcredist 2015, or it will close before opening the game window.

**Comment by renaudbedard** [comment]
To be clear : 
Prerequisites need to include VC++ 2015 x86 and .NET 4.6.
They have been added to the install script in Steamworks but the changes have not been published since it would affect 1.11 users, so just need to remember to publish them at launch!

**Comment by renaudbedard** [comment]
I decided against using my own build of MojoShader, using the official FNA ones don't have this issue.
