### ISSUE TITLE
Ghost platform after switching 2D/3D

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#110]
I have seen this glitch many times:
http://veg.by/z/2016-07-12-08-43-34-c31e51fe.png
http://veg.by/z/2016-07-12-08-48-16-e6f88e8e.png

Long time I didn't know how to reproduce it easily. It thought that it happens sometimes after pause menu or map. But now I have found a way to reproduce it easily. Just switch between 2D/3D views when any flying platform is visible. As the result you will get a ghost platform (a copy of the flying platform).

You can't jump on this ghost platform. It disappears after first rotating (projection changing). So, it is just a graphical glitch.

I have seen similar bug in the v1.11, so this version is also affected.

**Comment by flibitijibibo** [comment]
This is an issue with the trile culling, which has been around since the 360 version... I got the case where this happens from the map, but not this one. I'll look tomorrow.

**Comment by flibitijibibo** [comment]
This is fixed for the next update.
