### ISSUE TITLE
"Pause on lost focus" bug

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#115]
The game doesn't allow to open the pause menu when the inventory cube is shown. But it is still possible to open pause menu, when "pause on lost focus" setting is enabled. Just minimize the game and activate it again. As the result you will be in the pause menu. And it may cause some problems. For example, if you open video settings and change them, gameplay will look like this: http://veg.by/z/2016-07-14-07-57-27-09009e07.png

Inventory mode pauses the game by itself, so it is not needed to pause the game again on lost focus in this case.

**Comment by flibitijibibo** [comment]
Fixed in the next build, we'll just ignore lost focus whenever the game level isn't rendering, so the pause menu shouldn't override similar situations.

**Comment by vrubleg** [comment]
There is another insignificant problem. When "Pause on lost focus" is enabled, I think that it is better to mute all sounds when window isn't active.

Examples of problems:
1. When map is opened and game is minimized, game plays this nice "map" sound again and again.
2. Initial logo screen also plays music even game is minimized.
