### ISSUE TITLE
The game plays sounds when it is minimized

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#118]
Game plays sounds when it is minimized even when "Pause on lost focus" setting is enabled. I think that it will be better to mute all sounds when the window isn't active at least when "Pause on lost focus" is on.

Examples of problems:
1. When the world map is opened and the game is minimized, the game plays the "map" sound again and again.
2. Initial intro screens also play music even the game is minimized.

Not significant, but I think that it will be easy to fix.

**Comment by flibitijibibo** [comment]
Mute on Lost Focus wouldn't be too hard... it'd also be a bonus point on the PCGW checklist. I'll write this in tomorrow as a gameplay option.

**Comment by vrubleg** [comment]
An idea. It is possible to merge it with the Pause On Lost Focus setting.
On Lost Focus (or Lost Focus Action): None (or No) / Mute / Pause
Pause includes Mute, it seems logical :)

**Comment by flibitijibibo** [comment]
This is in the next build as part of pause on lost focus. Note that if POLF is disabled, sections that do not pause will still have audio, and this is currently by design.
