### ISSUE TITLE
Graphic glitches in CMY Cave.

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#12]
The portal colored lights can still be seen in the Pause menu :
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/CMY_Cave_1.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/CMY_Cave_2.png

Gomez is hidden by the portal :
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/CMY_Cave_3.png

Anticube light rays fully visible beyond the dark halo :
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/CMY_Cave_4.png

**Comment by renaudbedard** [comment]
- I couldn't repro the colored lights in the pause menu, but I still guarded against it (don't render in pause...)
- Gomez hidden by portal is also fixed
- Fixed the flare, still different than before I think, but looks okay to me 
  ![image](https://cloud.githubusercontent.com/assets/251134/11648108/71460a30-9d3e-11e5-95a4-858e808229c1.png)
