### ISSUE TITLE
The main window doesn't have an icon

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#120]
It would look nicer with an icon of the fez.exe.
http://veg.by/z/2016-07-22-16-28-19-b6bd137f.png

**Comment by flibitijibibo** [comment]
Renaud will just need to add a FEZ.bmp to the game folder, I've got that available so we'll throw it in the next update.

**Comment by vrubleg** [comment]
BTW, fez.exe itself also lost its icon. v1.11 has an icon.

**Comment by flibitijibibo** [comment]
Checked up on this in the csproj, the Game.ico is definitely referenced... maybe an outdated thumbs.db or something? I'm just reading a bunch of XML files though, maybe Renaud has a better idea of what's up.

**Comment by renaudbedard** [comment]
I'll take a look, that part is on me!

**Comment by vrubleg** [comment]
It seems that I was wrong about the icon in the resources of the fez.exe, sorry. But the main window doesn't have an icon, so the main issue is right.

**Comment by renaudbedard** [comment]
Window icon, dock icon and file icon confirmed working on my setup. :)

**Comment by vrubleg** [comment]
That's a little bit strange to load an icon for the window from the external 256×256 bmp file while the same icon is available in the exe resources, but at least it works now, thanks.

**Comment by vrubleg** [comment]
BTW, I had created this patch for SDL: https://bugzilla.libsdl.org/show_bug.cgi?id=3405
If this patch will be accepted, SDL will use current icon from the resources as a default window icon (on Windows).

**Comment by vrubleg** [comment]
The patch is accepted: https://hg.libsdl.org/SDL/rev/5c06c3aaca68
So, if you will use the latest revision of the SDL, you can remove fez.png. As the result the first icon from the fez.exe will be used automatically.

**Comment by vrubleg** [comment]
https://libsdl.org/download-2.0.php

SDL v2.0.5 is released, so you may just use this version of the SDL, and it will use the default icon from the resources. The fez.bmp will not be needed.
