### ISSUE TITLE
Performance regression in interior industrial room

### ISSUE THREAD

**Issue by renaudbedard** [renaudbedard/fez-1.12-issues#125]
As found by Gyoo on stream, looks like 1.12 has a performance issue in the industrial interior room that leads to industrial works from the lighthouse. (the one that has transparent platforms and a chest at the top)

**Comment by Gyoo** [comment]
Adding more data : https://secure.twitch.tv/gyoo_/v/80318388

I've let the next room in the video since I've noticed some chopiness on it too, after taking the shortcut door. It probably has something to do with it since, when I went through this room the first time at the beginning of the run, performance was completely fine.

**Comment by flibitijibibo** [comment]
It seems like this is tied to #113. We should probably profile memory/GC usage in addition to checking up on stuff that's now on Draw instead of Update. Could be that we're doing too much work in Draw at the wrong time, could be that we've got some stupid leak and the GC is having fun with us.

**Comment by renaudbedard** [comment]
I just tested... it's an issue with disabling multi-threading. Since the music streaming depends on FEZ's internal thread pool, the fact that speedrun mode sets the game in singlethreaded mode makes all the music streaming inline, and the industrial level has a lot of music to stream, especially when it starts up and it has to cache like 20 tracks to keep them in sync.

I see two possible workarounds for this : 
- We don't set singlethreaded mode for speedrunning. It's kind of a non-issue because even multithreaded loadings are not very long, and they don't count in the in-game timer anymore.
- We set up music streaming to be enabled whether or not singlethreaded mode is enabled. I'm not fond of that because the whole point of singlethreading is to avoid any and all threading-related bugs, whether they come from music or anything else.

**Comment by flibitijibibo** [comment]
I'll take a look at optimizing the music... even if we threaded the music the DynamicSoundEffectInstance callbacks still get hit on FrameworkDispatcher.Update, so this is probably a good time to look at the problems that Maik pointed out when making FNADroid.

**Comment by renaudbedard** [comment]
Fixed by making the thread that does music precaching run even if you make the game singlethreaded! We agreed that this is the best solution and does address the issue.
