### ISSUE TITLE
[SDL2] Unrecognized keycode "178"

### ISSUE THREAD

**Issue by renaudbedard** [renaudbedard/fez-1.12-issues#126]
In @Gyoo's logfile for another bug report, there are a bunch of log messages for an unrecognized scancode.

http://pastebin.com/UZdrzdMW

`[FNA] ERROR : KEY/SCANCODE MISSING FROM SDL2->XNA DICTIONARY: 178 SDL_SCANCODE_GRAVE`

Gyoo : can you try to figure out which key on your keyboard is causing that log call, it's probably the key on the leftmost, topmost row (left of the 1 number key). Can you tell us what that key does in your keyboard layout?

**Comment by flibitijibibo** [comment]
Once we know what key it is we can submit this as an SDL report.

That said, this reminds me to look into integrating the FNA GetKeyFromScancode extension to make other keyboard layouts work without reassigning keys. I'll look at this tomorrow.

**Comment by flibitijibibo** [comment]
The next build will default to keys based on the active keyboard layout. So, on AZERTY, the WASD setup should instead be ZQSD.

Still wanna know what this 178 key is though... the suspense is killing me!

**Comment by Gyoo** [comment]
Sorry for the late reply. This is ² on my keyboard.
This also happens to be the key I use to split in Livesplit (that software uses global hotkeys). That's why I have to press it every now and then.

**Comment by flibitijibibo** [comment]
Looked through other keyboards and couldn't find a keyboard that had ² as a standalone symbol, just as a character you can generate with AltGr (and that will only show up in TextInputEXT).

Ended up just throwing it into FNA's translation dictionary, maybe we can get it into SDL2 at some point later:

https://github.com/FNA-XNA/FNA/commit/873f0e22a005071cb959f0f59415b57c166e6c6f

**Comment by Gyoo** [comment]
Fyi, ² is a standalone key on every single AZERTY keyboard (French keyboards)

**Comment by flibitijibibo** [comment]
Right. I was worried others might have it as well in other locations, but it seems they're only found in as AltGr symbols, except for AZERTY. So we _should_ be safe...
