### ISSUE TITLE
Windowing issues

### ISSUE THREAD

**Issue by renaudbedard** [renaudbedard/fez-1.12-issues#127]
When toggling fullscreen/windowed on Windows (not tested on other platforms), there are view scaling issues in the menus.

Additionally, when using the "supersampled" scaling mode, toggling fullscreen/windowed overrides the supersampled backbuffer (does not show supersampling) until you confirm video changes a second time.

These are likely related to FNA problems.

**Comment by flibitijibibo** [comment]
I believe this gets it for us, needs verification on Windows first:

https://github.com/FNA-XNA/FNA/commit/e91924395e3dd917f96169847233756db8bb8831

**Comment by renaudbedard** [comment]
Seems good now, thanks Ethan!
