### ISSUE TITLE
Weird resolutions handling after restarting

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#128]
The latest version has some new strange issue with resolutions.

How to reproduce:
1. Choose some resolution with a non-native aspect ratio, e.g. 1280×1024 (fullscreen, full aspect).
2. Restart the game.
3. Polytron logo will have distorted proportions, as it was in the previous beta versions. But most other things, inclusive menu and gameplay, will be rendered in native resolution (1920×1200 in my case).
4. If you open game settings and just apply the same resolution, rendering of the menu will be switched from 1920×1200 to 1280×1024, as it have to be.

Maybe it is connected to the https://github.com/renaudbedard/fez-1.12-issues/issues/127

**Comment by flibitijibibo** [comment]
Yeah, this is probably the same issue. Let's check in the next build though, after FNA's updated.

**Comment by renaudbedard** [comment]
Yep, I can't reproduce this issue with the latest changes for #127.
