### ISSUE TITLE
"Reset to defaults" still sets 1280×720 as the default resolution

### ISSUE THREAD

**Issue by vrubleg** [renaudbedard/fez-1.12-issues#129]
On the first run the game uses native resolution as the default resolution. It will be better to set this resolution when users presses "Reset to defaults" button (in the graphics settings, here http://veg.by/z/2016-08-04-09-18-06-a12f8369.png) also.

**Comment by flibitijibibo** [comment]
Fixed in the next build; this actually worked if your display didn't support 1280x720, but no sense checking for that when we know the default mode works...
