### ISSUE TITLE
Tilted cube in Hexahedron filling cutscene

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#130]
https://www.twitch.tv/gyoo_/v/81712228

On this particular attempt the hexahedron rotated in a weird fashion which resulted in the cube not being on the correct face at the end of the rotation.

I was playing in 1920*1080, if that helps.

**Comment by Gyoo** [comment]
EDIT : changed description and video link

**Comment by renaudbedard** [comment]
Fixed! Also fixed the "freefall" sound effect that was triggered in this cutscene for no reason, the issues were related.
(aaaaaalso.... I had to add a bit of time to that cutscene to make the "sssssshhhhhHHHH" sound effect match up with the visual of what's happening, which is something that's been annoying me forever)
