### ISSUE TITLE
5.1 surround speaker

### ISSUE THREAD

**Issue by KainXVIII** [renaudbedard/fez-1.12-issues#132]
Sound effects and "voice" played from rear speakers, which is wrong, It was fixed some time ago, but broken in patch 1.12 again.

**Comment by flibitijibibo** [comment]
Wonder if it just needs alsoft.ini again; go grab this and inside the bin folder should be an alsoft-config.exe:

http://kcat.strangesoft.net/openal-binaries/openal-soft-1.17.2-bin.zip

Run through that, throw it in the game folder, see if that deals with it.

**Comment by KainXVIII** [comment]
Either it don't work for me or i don't understand your instructions, sorry!

**Comment by flibitijibibo** [comment]
Actually, let's try this... open up `%APPDATA%\alsoft.ini` and replace everything in the file with this (or create it with notepad if it doesn't exist):

```
layout = fl=-90, fr=90, fc=0, sl=-178, sr=178, bl=-179, br=179
```

**Comment by KainXVIII** [comment]
I created alsoft.ini in Fez folder with your settings - still don't work.

**Comment by flibitijibibo** [comment]
Oh, dear - it appears I've had a long-standing regression in FNA's audio engine. Can you throw this FNA.dll into your game folder and try one more time?

http://www.flibitijibibo.com/FNA.dll.zip

**Comment by KainXVIII** [comment]
Yes! Now it fixed, thank you.

**Comment by flibitijibibo** [comment]
Cool, we'll roll that into the quickpatch later today.

Given the nature of the issue you may be unsurprised to find that this was the fix:

https://github.com/FNA-XNA/FNA/commit/c7b7f24fafdfe28f186bc860149f62b92ced73b5

**Comment by renaudbedard** [comment]
Windows build with this fix is live on Steam right now.
