### ISSUE TITLE
FEZ Instantly Crashes When Connecting PS3 Pad via Bluetooth

### ISSUE THREAD

**Issue by The-King-of-Toasters** [renaudbedard/fez-1.12-issues#133]
I'm running FEZ on my Thinkpad T420 (i7-2620M, NVS 4200M, Fedora 24) and whenever I connect my Dualshock 3 controller through bluetooth it instantly crashes. I can confirm this behaviour doesn't occur in patch 1.11, nor when I'm using the keyboard exclusively. My debug log is [Here](https://github.com/renaudbedard/fez-1.12-issues/files/426869/2016-08-19.Debug.Log.5.txt) along with a recording of the crash [Here](https://sendvid.com/a68xclf3).

**Comment by flibitijibibo** [comment]
Looks like this was introduced at the last minute, as part of the PS hotplugging update. Will have this fixed real quicklike!

**Comment by flibitijibibo** [comment]
Okay, just pushed a small hotfix that deals with this (only meant to push a hotfix for adding a singlethreaded toggle, but hey).

Can you try the latest build and see if this still happens?

**Comment by ghost** [comment]
Does the same for me with a wired PS4 pad connected

**Comment by flibitijibibo** [comment]
@AlanMWalker If you're on Linux/Mac, give the latest Steam build a try. For Windows, it might be a little while (Win32 build is separate from the rest).

**Comment by ghost** [comment]
@flibitijibibo Cheers, I'll just use PC controls for now. But as soon as I can hook up my PS4 pad I will! I'll keep my eyes on the Fez updates

**Comment by The-King-of-Toasters** [comment]
Yep, that fixed it for me. Thanks @flibitijibibo!

**Comment by renaudbedard** [comment]
Windows build with this fix is live on Steam right now.
