### ISSUE TITLE
Bad detection of screen resolution 

### ISSUE THREAD

**Issue by AppleSeed2010** [renaudbedard/fez-1.12-issues#135]
Hi,

I have a dual monitor setup: 
- one screen is 4:3
- the second one is 16:9
  The game detect only the 4:3 screen resolution:
- In fullscreen, the game take 1280x1024 resolution (4:3 screen) and appear on the 16:9 screen => black box to fill the screen right with game on the left...
- In window mode, resolution is locked in 1280x1024 and i can't change it in the option panel. => why not add a free resolution option or ability to resize window like any application ? (or command line option like -screen=1920x1061 -windowed)

I'm under nvidia@archlinux with Fez 1.12.

By the way, thx for the great game :)

**Comment by flibitijibibo** [comment]
You can edit `~/.config/FEZ/Settings` if you want to force resolutions in fullscreen mode. That said, it's worth noting that FNA's default display options are based on the first display found by SDL's display enumeration, and display modes are stored per-display. I would compare the behavior of the game on the primary display vs. the Xorg display configuration.

**Comment by AppleSeed2010** [comment]
With the modification of the Settings file, windowed mode with my strange resolution (1920x1061) works nice. Best regards.

**Comment by AppleSeed2010** [comment]
Some more test: the window resolution works but the game is somewhat "zoomed".
If i go back in fullscreen mode in 1920x1080 (native fullscreen mode), the game is badly scaled. If i change the scale mode in the option, the game go back to 1280x1024 with black border.

**Comment by flibitijibibo** [comment]
Yeah, you'll have to adjust the scale mode in Settings too. So you can do PixelPerfect for ScaleMode and it should be okay.

**Comment by AppleSeed2010** [comment]
Another problem related: the camera don't move at all and do not follow us. Same with camera move button.
After a switch of first screen in xorg file **and** modification option useCurrentMode to true in fez Setting file : the game works ok (and moving camera too). All the scalemode work now.
Thanks for the flash reply ;)
