### ISSUE TITLE
Game doesn't load from Steam =(

### ISSUE THREAD

**Issue by thisisemad** [renaudbedard/fez-1.12-issues#136]
[[2016-08-19] Debug Log.txt](https://github.com/renaudbedard/fez-1.12-issues/files/427913/2016-08-19.Debug.Log.txt)

Hope this helps you to fix the issue =)

**Comment by renaudbedard** [comment]
Is this related to #133, @flibitijibibo?

**Comment by thisisemad** [comment]
Just putting it out there that this happens when using a PS4 or Xbox One controller via USB, or no controller - just doesn't load at all. Had zero issues with the prev version.

**Comment by flibitijibibo** [comment]
Yeah, this is #133. Shouldn't happen next update for Windows.

**Comment by thisisemad** [comment]
Just wanted to say how the game redownloaded (Steam didn't update), but is suddenly working again all of a sudden.

Thanks so much for being so helpful you guys!
