### ISSUE TITLE
Threading-related crash in sky update

### ISSUE THREAD

**Issue by renaudbedard** [renaudbedard/fez-1.12-issues#137]
Reported by a friend on his Macbook Air, OS X.

Happened during a level door transition.

> (17:13:47.374) [Unhandled Exception] ERROR : System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>   at System.ThrowHelper.ThrowInvalidOperationException (ExceptionResource resource) [0x00000] in <filename unknown>:0 
>   at System.Collections.Generic.List`1+Enumerator[FezEngine.Components.SkyHost+CloudState].MoveNextRare () [0x00000] in <filename unknown>:0 
>   at System.Collections.Generic.List`1+Enumerator[FezEngine.Components.SkyHost+CloudState].MoveNext () [0x00000] in <filename unknown>:0 
>   at FezEngine.Components.SkyHost.UpdateLayerAndCloudParallax () [0x00000] in <filename unknown>:0 
>   at FezEngine.Components.SkyHost.OnViewChanged () [0x00000] in <filename unknown>:0

**Comment by Terrev** [comment]
Had a crash that might be related to this, happened while going through the door from the classroom to villageville (3D versions):

[http://pastebin.com/xYnWaecT](http://pastebin.com/xYnWaecT)

Windows 7, intel i7... Any other info that'd be helpful?

**Comment by renaudbedard** [comment]
Yep, same issue @Terrev. Looking into it!

**Comment by renaudbedard** [comment]
Should be fixed, the Windows build is live. Let me know if it happens again!
