### ISSUE TITLE
Crash with special layout

### ISSUE THREAD

**Issue by drogeek** [renaudbedard/fez-1.12-issues#138]
I noticed the game wouldn't launch if my current layout is bépo on Linux (you can change your layout for instance doing setxkbmap fr bepo)

[[2016-08-20] Debug Log.txt](https://github.com/renaudbedard/fez-1.12-issues/files/428107/2016-08-20.Debug.Log.txt)

**Comment by flibitijibibo** [comment]
Oh dear, this one was my fault... would you believe that the é in bépo is the key that we couldn't find? >_<

That said, I don't think I can actually map that in XNA... I can at least drop the warning message to prevent spam, but you may want to export FNA_KEYBOARD_USE_SCANCODES to prevent the key bindings from getting borked. Via Steam you can do this as a launch option:

`FNA_KEYBOARD_USE_SCANCODES=1 %command%`

That's a little trick in all of my FNA titles, for what it's worth :)

In any case, this crash should be fixed on Steam now (Linux/Mac, Windows should arrive later in the day).
