### ISSUE TITLE
Xbox One Controller Left Trigger Can Double Rotate

### ISSUE THREAD

**Issue by belak** [renaudbedard/fez-1.12-issues#139]
It's sort of random and I don't have a consistent way of reproducing this, but I'm using an Xbox One controller with a wireless adapter (on PC) and most of the time when I use the left trigger, it rotates two sides, rather than one. The right trigger doesn't appear to do this.

I've tried disabling multithreading mode and it still does this.

Also worth noting, if I only press the trigger down about a third of the way, it only rotates once.

I checked the logs and didn't see anything relevant, but I can post it if you want.

**Comment by flibitijibibo** [comment]
Just as an early check, is this Windows 10? After the Anniversary Update I've been a bit paranoid about possible breakage in the Xbox One driver... though double input like the one from the AU wouldn't quite break in that way.

One thing we can check out is a test build of SDL, which you can grab here:

https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio/sdl-visualstudio-2731.zip

Inside SDL/lib/win32/ should be SDL2.dll, throw that into the game folder (overwriting the old one) and see if that improves anything.

**Comment by belak** [comment]
Yes, I'm on Windows 10 and I have the Anniversary Update. It looks like that SDL build fixes it though.

Thanks for the quick response!

**Comment by flibitijibibo** [comment]
Merged the recent SDL2 Windows changes into the FNA SDL mirror. @renaudbedard, when doing the next update be sure to grab it from fnalibs.tar.bz2:

http://fna.flibitijibibo.com/archive/fnalibs.tar.bz2

**Comment by renaudbedard** [comment]
Pushed updated SDL library to Steam on Windows!
