### ISSUE TITLE
Slow-down when switching resolutions

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#14]
Switching between resolutions multiple times without resuming can slow down everything.

Alt-tab will fix everything.

**Comment by renaudbedard** [comment]
I think initially in your report you mentioned this was related to MSAA, it's not?

**Comment by Gimlao** [comment]
This is a new issue. =p

I forgot to test it without MSAA, by the way.

**Comment by Gimlao** [comment]
Yes, with MSAA x16 and x32, everything in the pause menus is slowing down when switching between resolutions near from 1920x1080.

**Comment by renaudbedard** [comment]
See #16
