### ISSUE TITLE
Fez doesn't recognize gamepad

### ISSUE THREAD

**Issue by Nufirdy** [renaudbedard/fez-1.12-issues#141]
Hello there. I saw that fez got an update and I decied to play it for a bit. Before the update I played with my gamepad but now fez doesn't recognize it at all. Using joytokey didn't help because dpad mappings don't work ingame. I use Fusa Gamepad it's a psp program that makes it usable as gamepad.
I don't know what other information to give you
Hope for your help
sorry for bad english

**Comment by flibitijibibo** [comment]
We should be able to support it without stuff like joy2key - can you try configuring it in Big Picture Mode? There should be a gamepad config option in the menu, and after that's done Steam will send your config to the game, and then we can read it and map it in-game.
