### ISSUE TITLE
Game performs "First Time Setup" each time it is opened

### ISSUE THREAD

**Issue by Nicholas-Steel** [renaudbedard/fez-1.12-issues#143]
Each time I open the game it will perform a "First Time Setup" process and trigger a UAC prompt, other than this it seems to work fine? Windows 10 x64 Anniversary Update 1607

Demonstration: https://youtu.be/m2zAoTSbBzs

**Comment by flibitijibibo** [comment]
That's probably Steam trying to install .NET or the Visual C++ redist packages. I'm not sure why it doesn't successfully install them the first time though... does UAC tell you what's trying to run?

**Comment by renaudbedard** [comment]
The redistributable list on Windows is .NET Framework 4.6 and Visual C++ 2010 x86 : 

https://www.microsoft.com/en-ca/download/details.aspx?id=48130
https://www.microsoft.com/en-ca/download/details.aspx?id=5555

Worst case, try to install them manually and see if Steam still tries to do it on launch?

**Comment by Nicholas-Steel** [comment]
Steam does not show that it is installing any of the dependencies/is skipping them because they were already installed during the first time I ran the game after downloading and opening the game (I redownloaded the whole game after hearing the v1.12 patch was released). The UAC prompt says the following is causing the UAC prompt.

"E:\Steam Games\bin\steamservice.exe" /installscript "E:\Steam Games\steamapps\common\FEZ\runasadmin.vdf" 224760

**Comment by flibitijibibo** [comment]
Oh, you know what that might be - @renaudbedard, was that needed back when you were doing file copies for OpenAL Soft? I can disable that from here if you want.

**Comment by Nicholas-Steel** [comment]
Demonstration: https://youtu.be/m2zAoTSbBzs

**Comment by flibitijibibo** [comment]
Hm, I can't seem to find a way to get rid of that script. Can you go into the game folder and delete the CommonRedist folder, and see what happens then?

**Comment by Nicholas-Steel** [comment]
Deleting the _CommonRedist folder does not accomplish anything useful. Deleting installscript.vdf from the FEZ folder however does resolve the issue. So I will assume that that file is meant to be deleted after initial setup completes successfully.

**Comment by flibitijibibo** [comment]
Interestingly it's meant to be there all the time, but why it runs installers that are installed I'm not sure. Unfortunately there's not much we can do; I was looking this up on the Steamworks discussions and it turns out this has been a problem since, at minimum, November 2014. You may have to file a support ticket with the Steam team:

https://support.steampowered.com/

It's good that there's still a workaround, but for now that's the best we've got.
