### ISSUE TITLE
Game confuses Gomez Z-Axis

### ISSUE THREAD

**Issue by Nicholas-Steel** [renaudbedard/fez-1.12-issues#146]
Demonstration: https://youtu.be/7OaiXY-S4VY

From the door you used to enter this area, you can jump Left from the door and rotate the screen counter-clockwise once to land where you're not supposed to/meant to climb the vines to reach.

**Comment by renaudbedard** [comment]
That's a known limitation of the collision system that happens when you're "sandwiched" between two tiles. There's a bunch of places in the game where it's reproducible, but it's not a trivial issue to address so it's been laid to rest in the bug cemetary.

**Comment by Nicholas-Steel** [comment]
Okay, fair enough.

**Comment by renaudbedard** [comment]
To clarify the intent of this issue repo, I added a section to the readme : https://github.com/renaudbedard/fez-1.12-issues/blob/master/README.md

I don't want to make it seem like I'm disregarding any and all problems people have with the game! I just don't intend to do major changes to the game that don't fix 1.12-specific issues at this point.
