### ISSUE TITLE
Perpetual loading screen

### ISSUE THREAD

**Issue by Nicholas-Steel** [renaudbedard/fez-1.12-issues#147]
I encountered a perpetual loading screen (No in-game error message or crash) with the yellow loading cube constantly spinning in the bottom right corner. This problem was encountered in the previous Experimental build (a new version got downloaded today as soon as I forced the game shut!)

I was traveling through one of the many doors in the populated ruins (the ruins where you can access the Star Transporter and end the game).

(12:19:45.139) [FNA] INFORMATION : Controller 0: Generic DirectInput Controller
(12:19:45.889) [Version] INFORMATION : 1.12, Build Date : 2016-08-23 23:19:43
(12:19:46.065) [FNA] INFORMATION : IGLDevice: OpenGLDevice
(12:19:46.067) [FNA] INFORMATION : OpenGL Device: GeForce GTX 760/PCIe/SSE2
(12:19:46.068) [FNA] INFORMATION : OpenGL Driver: 4.5.0 NVIDIA 372.54
(12:19:46.069) [FNA] INFORMATION : OpenGL Vendor: NVIDIA Corporation
(12:19:46.070) [FNA] INFORMATION : MojoShader Profile: glsl120
(12:19:46.078) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(12:19:46.103) [Instancing] INFORMATION : Hardware instancing is enabled
(12:19:46.138) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(12:19:46.141) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
(12:19:46.143) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(12:19:46.145) [SettingsManager] INFORMATION : Backbuffer is 1920x1080
(12:19:46.147) [SettingsManager] INFORMATION : VSync is on
(12:19:46.149) [SettingsManager] INFORMATION : Multisample count is 0
(12:19:46.246) [Threading] INFORMATION : Multithreading is enabled
(12:19:46.827) [Intro] INFORMATION : First draw done!
(12:19:48.499) [StaticPreloader] INFORMATION : SharedContentManager preloaded.
(12:19:50.266) [StaticPreloader] INFORMATION : Music library initialized.
(12:19:50.286) [StaticPreloader] INFORMATION : Volume levels loaded.
(12:19:50.373) [StaticPreloader] INFORMATION : Animations filled.
(12:19:50.376) [StaticPreloader] INFORMATION : Text scroll pre-initialized.
(12:19:50.377) [StaticPreloader] INFORMATION : World map pre-initialized.
(12:19:50.379) [StaticPreloader] INFORMATION : Pause menu pre-initialized.
(12:19:50.893) [Intro] INFORMATION : Preloading complete.
(12:20:05.098) [Intro] INFORMATION : Level load complete.
(12:20:10.914) [Intro] INFORMATION : Intro is done and game is go!
(12:37:43.966) [FNA] INFORMATION : Using EXT_swap_control_tear VSync!
(12:37:43.967) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
(12:37:43.969) [SettingsManager] INFORMATION : Screen mode is : Fullscreen
(12:37:43.970) [SettingsManager] INFORMATION : Backbuffer is 1920x1080
(12:37:43.972) [SettingsManager] INFORMATION : VSync is on
(12:37:43.973) [SettingsManager] INFORMATION : Multisample count is 0
(12:49:49.691) [Unhandled Exception] ERROR : System.ArgumentOutOfRangeException: Index must be within the bounds of the List.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at Microsoft.Xna.Framework.GameComponentCollection.InsertItem(Int32 index, IGameComponent item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at FezEngine.Tools.ServiceHelper.AddComponent(IGameComponent component, Boolean addServices)
   at FezEngine.Components.NpcHost.LoadCharacters()
   at System.Action.Invoke()
   at FezEngine.Services.LevelManager.OnLevelChanged()
   at FezGame.Services.GameLevelManager.ChangeLevel(String levelName)
   at FezGame.Components.Actions.EnterDoor.DoLoad(Boolean dummy)
   at FezEngine.Tools.Worker`1.Act()
   at FezEngine.Tools.PersistentThread.DoActualWork()
   at Common.Logger.Try(Action action)

**Comment by renaudbedard** [comment]
D'oh! Yep, that was my bad. This bug would've happened in the new update and in the experimental branch.
I just fixed it and ~~pushed to default branch~~. (actually in experimental now, since it's not ready for prime-time)
