### ISSUE TITLE
Artifacts in Borderless window + uncommon resolution

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#158]
Since I started playing in 1776*1000 borderless window, I figured some artifacts in Gomez's animations and some other stuff, see pictures below.

http://i.imgur.com/YXeAhH8.jpg (above Gomez' head)
http://i.imgur.com/KuqA179.jpg (feet)
http://i.imgur.com/NYwJURU.jpg (Scroll)
http://i.imgur.com/NAZhCqb.jpg (above head + scroll again)

It doesn't happen in 1080p full screen

**Comment by vrubleg** [comment]
Probably, it is a problem in your GPU driver. I have similar random glitches in one game when specific version of the GPU driver is used, and I don't have such problem in the game when any other version of the GPU driver is used. So, you can try to update or downgrade your GPU driver to check if it will be always reproducible.
