### ISSUE TITLE
Little freezes when pausing / resuming with MSAA enabled

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#16]
The game will freeze for some seconds when pausing and resuming the game with MSAA x16 or x32 enabled, with resolutions near from 1920x1080.

**Comment by Gimlao** [comment]
Actually, maybe I'm duplicating https://github.com/renaudbedard/fez-1.12-issues/issues/14.

**Comment by renaudbedard** [comment]
I'm going to say that 16x and 32x MSAA demand very high-resolution depth textures, which means these hitches are going to occur...
If you don't see hitches at 8x MSAA, I'll mark this as "wontfix".
(Also since it's not officially supported, I don't feel very compelled to look into it)
