### ISSUE TITLE
All structures are Invisible

### ISSUE THREAD

**Issue by struddles73** [renaudbedard/fez-1.12-issues#162]
Ever since I first began gameplay, every building or other large structure becomes invisible after their initial appearance on screen. For example, the first time I visited the lighthouse island I could see the lighthouse, large tree, etc. but now every time I go there I don't see them at all. I do, however, see the vines wrapping around the lighthouse. I've tried restarting the game already but the problem still persists. Would re-downloading the game fix the issue? I would like to avoid doing that as I would rather not restart my whole game, but if it is necessary to fix the problem then I would still do it.

**Comment by flibitijibibo** [comment]
Have any hardware information? Depending on that it may just be a matter of flipping a few switches, but we'll need to know that first.

**Comment by struddles73** [comment]
I'm not sure exactly what info you need, but I'm running the game on a Dell Latitude E6420 with Windows 10. My RAM is 4GB, and my processor is Intel(R) Core (TM) i5-2520M CPU @ 2.50GHz, 2501 Mhz, 2 Cores, 4 Logical Processors. Does this help?

Thanks for the assistance!

**Comment by flibitijibibo** [comment]
A couple things to try:
- Enable singlethreaded mode in the game options menu
- Disable hardware instancing in the video options menu

**Comment by struddles73** [comment]
That did it! Thanks so much for the help:)
