### ISSUE TITLE
Game files are all corrupted after the new 1.12 update. (Even after uninstalling/reinstalling it)

### ISSUE THREAD

**Issue by ghost** [renaudbedard/fez-1.12-issues#164]
When the new update came out Fez wouldn't update saying content still encrypted so I uninstalled it and reinstalled it and the update worked. When I started the game all the main screens where normal, but when I go into the saves even when making a new one the whole game's textures are in the wrong places and it is practically unplayable.
![fex](https://cloud.githubusercontent.com/assets/23514021/20374082/10b505c0-ac44-11e6-950b-1f08d31f4322.jpg)

**Comment by flibitijibibo** [comment]
That wouldn't happen to be Windows Vista, would it?

Can you grab the log files at %APPDATA%\FEZ\ and post them here? That data should give us some insight as to what is happening here...

**Comment by ghost** [comment]
[[2016-11-16] Debug Log.txt](https://github.com/renaudbedard/fez-1.12-issues/files/596417/2016-11-16.Debug.Log.txt)

**Comment by ghost** [comment]
and yes it is vista

**Comment by ghost** [comment]
The other files aren't supported,but they are just the save files

**Comment by flibitijibibo** [comment]
Taking a quick look it might be the driver - can you give this one a try?

http://support.amd.com/en-us/download/desktop/legacy?product=legacy2&os=Windows%20Vista%20-%2032

It looks like they've long since discontinued support for that hardware, but I actually can't tell how old your current version is. This should at least help stabilize things; features like hardware instancing already got turned off by the engine so now we're looking at bugs that never got fixed for the HD 3200 graphics cards.

**Comment by flibitijibibo** [comment]
Upon further inspection it appears your driver is well over 5 years old! This should certainly mitigate some problems for at least one other game, if not this one.

**Comment by ghost** [comment]
It wouldn't accept it, and also if it helps I tried it on my other laptop (windows 10) and it is doing the same thing as this one

**Comment by ghost** [comment]
At any chance I get I'll get the logs from it when possible, but my sister has homework on it and won't get off for anything.

**Comment by flibitijibibo** [comment]
Depending on the manufacturer for your PC they may have specialized driver updates for that specific model, but if you can find a way to sidestep that in favor of AMD's version then it should give you better results.

In the absolute worst case possible you could see if Linux Mint and the standard open source drivers give you a better result, but that's only if you can try without risking any of your data. For older cards (particularly Intel and AMD cards) the drivers over there are MUCH better, but you have to trade that for replacing your whole OS.

**Comment by ghost** [comment]
Okay I'll try it on my brother's new PC and if it doesn't work then there's no hope because the only linux I have is 15 years old and can only be connected to wifi through ethernet

**Comment by renaudbedard** [comment]
As far as I know this just means that the game thought that your display driver supported Hardware Geometry Instancing but it does not.
Try disabling Hardware Instancing in the Video Settings menu.
