### ISSUE TITLE
Gomez falls through rotating platform if he's climbing such a platform while it rotates

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#168]
https://www.twitch.tv/gyoo_/v/106312178

Video is self-explaining I think. This is pretty obnoxious since there's a few places where you are obligated to grab and climb these platforms.

**Comment by flibitijibibo** [comment]
Seems like it thinks the player is falling while that animation is going on, but that's coming from someone who doesn't touch the FEZ physics at all. Maybe this came from some of our 17ms mischief; I do remember rotating platforms getting a lot of attention during that time.

**Comment by renaudbedard** [comment]
It's a thing, but I'll lump it in with #33 (which may or may not be ever fixed, sorry!)
