### ISSUE TITLE
Missing/corrupted graphics when starting a game with 1.12 on Intel HD Graphics GPU

### ISSUE THREAD

**Issue by MrNostalgic** [renaudbedard/fez-1.12-issues#172]
So yesterday I bought the game, but when I started it to play this happend:

![imagen](https://cloud.githubusercontent.com/assets/25495650/22534042/23b9c05c-e8b7-11e6-98fa-9e14979b43f1.png)

![imagen](https://cloud.githubusercontent.com/assets/25495650/22534050/302d5dbc-e8b7-11e6-9250-4afc955f90f7.png)

Further areas of the game are even more glitched and the thing is basically unplayable

**Comment by renaudbedard** [comment]
This is most likely because the game thinks your PC supports Hardware Instancing but it does not.

Try going in the HELP & OPTIONS menu, then VIDEO SETTINGS, and turn HARDWARE INSTANCING to **OFF**.

Out of curiosity, what graphics card do you have?

**Comment by MrNostalgic** [comment]
Hey, it worked. Thanks a lot man. 

The graphics card I have is an Intel(R)HD Graphics

![imagen](https://cloud.githubusercontent.com/assets/25495650/22534574/968681a8-e8ba-11e6-85fe-f96ea41faaaf.png)
