### ISSUE TITLE
Quick pause-unpause stops music

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#18]
When pausing and then unpausing within about .2 seconds, the music cuts out upon resuming the game. However, doing a quick pause-unpause again makes it all go back to normal. This does not persist after going to an area which uses a different music track.

Environment sounds (birds chirping, cube bits ringing) are unaffected throughout.

**Comment by 0x0ade** [comment]
Also happens in single-threaded mode.

**Comment by renaudbedard** [comment]
Fixed, thanks!
