### ISSUE TITLE
Infinite loading when played a while

### ISSUE THREAD

**Issue by beldite** [renaudbedard/fez-1.12-issues#181]
I´ve reinstalled the game, even played a 2nd time, the most I´ve done is 70%, because when I get somewhere and enter a door, it sends me to an infinite loading screen, once I even waited half an hour and nothing happened.
What can I do?

**Comment by flibitijibibo** [comment]
Enabling single-threaded mode should fix this; enable this option in Game Options and after restarting, loading screens shouldn't hang anymore.

**Comment by beldite** [comment]
It worked, thanks a lot
