### ISSUE TITLE
Special door sound plays in pause menu

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#19]
When standing in front of the special connection doors (see image), if you pause the game and press the "enter the door" button, the sound effect plays for that door opening. The door does actually start to open, which you can see when you unpause.

While paused, the sound effect will just keep going until you unpause, instead of the amount of time it would take for the door to complete opening.

https://i.imgur.com/Ud57p9H.png

This was around in 1.11 as well.

**Comment by renaudbedard** [comment]
Fixed, thanks!
