### ISSUE TITLE
Ladder extends above visual height

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#20]
Some ladders and vines can be grabbed from higher than their visual appearance would let on. The engine "realizes" its mistake and makes Gomez fall as soon as the grabbing animation finishes.

http://imgur.com/VlNuJca

Admittedly, very low priority.

**Comment by renaudbedard** [comment]
Fixed! The velocity was lingering (and transitioning to zero) and it was enough to offset you too high vertically as you attached onto the ladder. I'm nullifying velocity as you start attaching to the ladder now.
