### ISSUE TITLE
Un-jump-off-able spots on vines

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#21]
If Gomez has grabbed onto vines in profile view, there are a few places on vines where Gomez isn't able to jump forward, and he instead reattaches himself to the vine after doing a short animation. Gomez must move up or down just a little bit before he can jump forward.

http://imgur.com/Slx3u21
http://imgur.com/MpdEhP7

**Comment by renaudbedard** [comment]
Yeah vines had been bugging me too... so I fixed them finally :)

Jump-off/reattach-to-vine logic used to be time-based, and based on the location of the last-grabbed-vine-tile, which was glitchy. 

Rules are now : as long as you're jumping up (positive Y velocity) away from a vine, you can't grab a vine that's less than 1.625 tiles away vertically, and 1 tile away horizontally from the last position you were when you let go. 
As soon as you start falling, you can re-grab any vine.

This feels good to me and still allows you to traverse vine walls pretty quick if you get the timing right. Let me know what you think.

Also fixed an ~~unreported~~ (actually was reported as #30) issue where moving on a vine would make Gomez hug walls, but only when moving, this would make you fall after rotating.

![fez_fall_vine](https://cloud.githubusercontent.com/assets/251134/11706397/66d2152e-9ec6-11e5-83bf-93a42db25853.gif)
