### ISSUE TITLE
Game crash if dialogue avoided in Gomez's house

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#22]
Situation: The Achievement Cube is collected in Gomez's house immediately after the Hexahedron breaks apart. Gomez goes through the door to 3D villageville without talking to Dot (i.e., he goes through the door before its dialogue pops up).

Result: The spinning reveal of 3D villageville does not occur. Dot does not perform the "whoa, that's your first anticube!" dialogue. The game soft-locks after Dot finishes introducing herself to Gomez.

**Comment by Gyoo** [comment]
I already talked about this one to @renaudbedard on Twitter. Apparently, there was already a hotfix, but somehow it's still happening.

**Comment by renaudbedard** [comment]
OK, was able to reproduce with your (and Gyoo's) steps. Fixed it for real, I think!
The dialogue kind of doesn't stop, it follows from DOT's intro speech to the "you found your first anti-cube" without interruption, but it doesn't soft-lock and it feels pretty good.
