### ISSUE TITLE
Spawning a Cube (combining 8 Cubebits) enables teleporters without having to collect the initial big Cube above it

### ISSUE THREAD

**Issue by Yauxo** [renaudbedard/fez-1.12-issues#26]
Setup: Be in a room with a Teleporter that'd activate once you'd collect the Cube above it. Grab your 8th Cubebit and stand next to the deactivated Teleporter. Once the Cubebit animation is done and a full cube was added, the Teleporter activates. If you happen to press "up" to activate it and collect the Cube that was supposed to activate the Teleporter in the first place, the game will semi-softlock. Switching saveslots and trying to re-enter the room will end in an actual softlock (endless loading screen).

Tested in the Infinite Climb Room. 
https://www.youtube.com/watch?v=I_nfF239dJc&feature=youtu.be

(Also, not sure if this is relevant to this, but whenever I changed slots while being stuck in the teleporter, I'd get that silent "woosh" sound in the main menu while being able to talk to Dot. When entering a slot, Gomez is invisible and bound to the ground. Trying to jump will leave you stuck in the air https://www.youtube.com/watch?v=TFHxZrFqxCY&feature=youtu.be)

**Comment by Yauxo** [comment]
Just found out that the endless loading screen is still a thing, even after restarting the game. I guess that file is ded (trying to access http://puu.sh/lGuFc/078bf0e51a.png)

**Comment by renaudbedard** [comment]
OK, fixed the initial issue you describe.

I think the change-slot/clear-slot code was broken in a bunch in the build you played so I'd say it's unrelated. Do try it again in the latest build if you can, though!

Also : endless loading screens usually hide a crash in the loading thread, check out the `Debug Log.txt` file for clues of what happened when they show up. Thanks!
