### ISSUE TITLE
Pillars in the Hexahedron cutscene are cut off

### ISSUE THREAD

**Issue by Yauxo** [renaudbedard/fez-1.12-issues#27]
How it should be v1.11 http://puu.sh/lGqYn/477eca1d9a.jpg
How it is v1.12 http://puu.sh/lFuq5/d98d839585.png

**Comment by renaudbedard** [comment]
I believe that's a side-effect of the removal of letterboxing in 1.12, it can be fixed by editing the level. Good catch!

**Comment by renaudbedard** [comment]
Fixed, thanks!
