### ISSUE TITLE
NPCs sometimes face a random/wrong direction when walking after talking

### ISSUE THREAD

**Issue by Yauxo** [renaudbedard/fez-1.12-issues#28]
Look for an NPC and talk to it in a view/angle where it cannot move. Switch view/angle to where the NPC is able to walk and most of the time they'll moonwalk to one of their spots.

https://www.youtube.com/watch?v=sYTqKUdBy9M

Pretty Minor

**Comment by renaudbedard** [comment]
Fixed! Bit more involved a fix than I would like, I had to change how rotation for NPCs is handled altogether... so let me know if you see something strange with NPCs elsewhere. I tested birds, owls, ZU villagers and VillageVille. I think it covers everything, but I may have forgotten something...

BONUS : Here's a fun bug I found while debugging your issue... (also fixed)
 https://youtu.be/AE86slWM7pE
