### ISSUE TITLE
Ghost-Vines

### ISSUE THREAD

**Issue by Yauxo** [renaudbedard/fez-1.12-issues#30]
Find a vine that's accessible from two angles and has some sort of stair pattern (a long vine and one that's not as long). Be on the short side, switch angles and crawl all the way down. Switch angle back and Gomez will be stuck on a ghost-vine. Jumping will free him.

https://www.youtube.com/watch?v=MGakKN0RiAU&feature=youtu.be

**Comment by Thejuikuen** [comment]
oh, i just submited the same thing, lol

**Comment by Yauxo** [comment]
Doesnt seem to work on every vine though. Might just be in that area

**Comment by MistahKurtz** [comment]
(swiggity swoogity) I think if Gomez is far enough down, he'll just fall when you rotate.

**Comment by renaudbedard** [comment]
Fixed when fixing #21 (see the GIF there)
