### ISSUE TITLE
Ivy in clock tower graphical error

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#31]
At the first lever you spin to line up ivy to scale the clock tower, sometimes the first panel of ivy will disappear although you are still able to climb it.

**Comment by renaudbedard** [comment]
I'm sure I've seen what you're talking about before, but I can't repro it currently. If you manage to grab a video of it happening it would help a lot!

**Comment by Thejuikuen** [comment]
I start from this side 

![6](https://cloud.githubusercontent.com/assets/16115136/11767272/c1fbe05c-a16d-11e5-83ad-6bb613099d3d.png)

Rotate to the right 2 times

![4](https://cloud.githubusercontent.com/assets/16115136/11767273/d22fff1c-a16d-11e5-9179-e1ca677763cf.png)

![5](https://cloud.githubusercontent.com/assets/16115136/11767274/d9484b24-a16d-11e5-8791-ab4f1792eab2.png)

**Comment by renaudbedard** [comment]
Thanks, fixed it with the repro steps! It was a culling issue which seems specific to rotating slabs/blocks like these.
