### ISSUE TITLE
Graphical glitch at windmill

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#32]
When switching perspectives from the right wall facing forward, to the front door facing forward, gomez will appear to clip into the wall of the windmill.

**Comment by renaudbedard** [comment]
Which level is this? Villageville?

Edit : nevermiiiind, obviously the windmill level.
![image](https://cloud.githubusercontent.com/assets/251134/11760084/dc7d4b1e-a05a-11e5-8410-c2389bb3a245.png)

**Comment by renaudbedard** [comment]
Fixed, and also fixed an owl visibility glitch that made it appear for one frame as you came from the windmill door, if you hadn't already collected him, no matter what time of day it was.
