### ISSUE TITLE
Forest Owl stops music

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#34]
Collecting the forest owl stopped the music...

**Comment by renaudbedard** [comment]
You mean this guy, right?
![image](https://cloud.githubusercontent.com/assets/251134/11831614/c52c82b0-a37d-11e5-8717-3e6a38439e71.png)

I tried reproducing and it seemed to work fine. Do you get this issue every time? What about other owls in other areas?

**Comment by flibitijibibo** [comment]
This one might not happen anymore now that the DynamicSoundEffectInstance behavior is a little different. Check this one out in the next FNA update for Windows.

**Comment by flibitijibibo** [comment]
Does this still happen for you @Thejuikuen? I think this has been resolved as an FNA issue, but if not then it's likely some wonky game logic...

**Comment by flibitijibibo** [comment]
Closing due to old age, but I think the new DSFI got it anyway.
