### ISSUE TITLE
Puzzles solve themselves after switching saves

### ISSUE THREAD

**Issue by Yauxo** [renaudbedard/fez-1.12-issues#35]
Solve puzzle (eg. Zu Unfold) on Slot A. Switch to Slot B (which didnt solve that puzzle yet), enter the same room and the puzzle will be solved automatically.

**Comment by renaudbedard** [comment]
Fixed it for this particular puzzle. I'll make sure state doesn't persist for other puzzles, but do you remember having seen it in another room?

Edit : Also fixed in the tetris and security question rooms.

**Comment by Yauxo** [comment]
IIRC Ive had this happen in some rooms where you have to move things from A to B, or place them in a specific order/position. 

I'll try rooms like the Weightswitch Temple and similar later

Edit: Couldnt reproduce, seems okay now
