### ISSUE TITLE
Dot showing blank preview image when near a Hub Teleport

### ISSUE THREAD

**Issue by Yauxo** [renaudbedard/fez-1.12-issues#36]
When standing near a Hub Teleporter, Dot tried to show me a image of the room Gomez would be teleported to (like when standing infront of a normal door)

![Hub](http://puu.sh/lGvpN/184549291c.jpg)

Ive had this happen multiple times, but dont know what caused that. Restarting fixes this (shows no preview)

**Comment by renaudbedard** [comment]
I've tried a bunch of things to reproduce this and couldn't get it to trigger. If anybody finds repro steps they would be greatly appreciated!

**Comment by flibitijibibo** [comment]
Have you gotten this to happen again? This was before a number of changes went into both FNA for sanity checks as well as FEZ itself regarding asset loading. This might have been fixed by accident; if you can't get it to happen again then we'll mark this as "probably fixed?".

**Comment by flibitijibibo** [comment]
Closing due to old age; I've not seen it yet on the hardware I've got running it...
