### ISSUE TITLE
Game won't start (MAC OS/X)

### ISSUE THREAD

**Issue by luisfcorreia** [renaudbedard/fez-1.12-issues#38]
Loads intro screen and then crashes.

El Capitan, 10.11.1 - fresh install

[Debug Log.txt](https://github.com/renaudbedard/fez-1.12-issues/files/49672/Debug.Log.txt)

**Comment by flibitijibibo** [comment]
This has been resolved in the latest revision.

**Comment by luisfcorreia** [comment]
confirmed
