### ISSUE TITLE
Lighting of animated background planes trailing behind a frame

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#39]
I can't remember seeing this in 1.11. This also happens in single-threaded mode.

It's not consistently one frame of the animation, but rather a half frame. Maybe caused by my low-specs machine running FEZ at low FPS.

![bildschirmfoto von 2015-12-03 19-20-21](https://cloud.githubusercontent.com/assets/1200380/11569648/50121f78-99f3-11e5-9e89-b09ca062f84e.png)

**Comment by renaudbedard** [comment]
I think the update order of planes changed so this may be introduced by 1.12. I for sure have never noticed it in 1.11... good eye!

**Comment by renaudbedard** [comment]
Fixed! Issue was that I updated the plane instances in the draw call, instead of in the lighting pre-pass.
