### ISSUE TITLE
Talking with NPCs near walls / void

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#4]
Gomez will not walk far enough before talking to NPCs near from walls / void.

He can also fall from the platform if he walks to the void. (hard to reproduce)

**Comment by Yauxo** [comment]
He'll also sometimes be pushed into walls http://puu.sh/lFu3W/7189d857f3.png (left)

**Comment by renaudbedard** [comment]
Both are fixed, thanks!

**Comment by renaudbedard** [comment]
(except the falling one, which I can't repro at the moment... if you catch it on video that would be swell)

**Comment by Gimlao** [comment]
https://dl.dropboxusercontent.com/u/12308005/Jeux/FEZ/screens/FEZ%2031_01_2016%2002_14_41.mp4 :3

**Comment by Gimlao** [comment]
Easy to duplicate here :

![](https://cloud.githubusercontent.com/assets/841935/15967318/75060c26-2f27-11e6-807e-5f3ae8594e72.png)

Talking with the ghost, with this view, Gomez will always fall.

**Comment by renaudbedard** [comment]
Fixed for good! It skips the walking routine if all the ideal places to walk to for talking cause Gomez to fall. So it's very possible that Gomez will overlap the NPC he's talking to in that case, but it sure is better than falling.
