### ISSUE TITLE
Dot black holes cutscene interactable when continuing game

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#40]
I can't remember it happening in 1.11, probably because I didn't encounter the message when continuing. I won't be wondered if it's a regression caused by merging my "Gyoo's Softlock" fix.

I haven't tested if this happens when entering the level other than continuing the game in 1.12.

![bildschirmfoto von 2015-12-03 19-24-48](https://cloud.githubusercontent.com/assets/1200380/11569929/bda22186-99f4-11e5-9114-fba38378f004.png)

![bildschirmfoto von 2015-12-03 19-24-56](https://cloud.githubusercontent.com/assets/1200380/11570012/3f12af10-99f5-11e5-869f-6e926f8cefb6.png)

**Comment by Yauxo** [comment]
I assume this is somewhat about being able to move while having text open? If so, I've had that with NPCs as well. Somehow I didnt get locked in place, but was able to move while someone was talking.

**Comment by 0x0ade** [comment]
Yes, as both (AFAIK) count as "cutscenes". I was able to trigger the NPC free talk by frame-perfectly timing (mashing) the move (left / right) and talk buttons. The main difference between the DOT and NPC glitch is that I'm able to do more with DOT (climb, jump) while the NPC text would cancel.

**Comment by renaudbedard** [comment]
To be clear : talking to NPCs or DOT should lock you in, you shouldn't be able to move. I guess you all know that, but that's not a new feature if you can, it's a bug.

I fixed this particular glitch with DOT speech as you continue game. I'm pretty sure it happened in 1.11 too.
If there are other instances where you're free or soft-locked, log as separate bugs plz!
