### ISSUE TITLE
Gomez able to hang mid-air

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#41]
This is also possible in 1.11 and just a minor issue / annoyance.

When running towards an edge with high enough speed and pressing the "climb down" combo at the right time, Gomez will climb down while moving horizontally.
Interaction with the cliff resets Gomez to the edge. Rotating puts him back to where he belongs.

![bildschirmfoto von 2015-12-03 19-21-09](https://cloud.githubusercontent.com/assets/1200380/11572053/a46d1cf6-99ff-11e5-80e6-f5418c4e508b.png)

**Comment by renaudbedard** [comment]
Definitely minor (and hard to repro, I ended up lowering to a corner ledge-grab instead most of the time!), but hey, why not. Fixed!
I kill horizontal velocity when you start the action now. Feels a bit more robotic but hopefully that's fine.
