### ISSUE TITLE
OoB in Boiler Room

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#42]
https://www.youtube.com/watch?v=V297ytao2Ng

Procedure :
- Enter boiler room
- Walk behind the table until you're behind the boiler
- Jump + RT

Also possible on the other side as shown in the end, but I couldn't figure out exactly how it happens

**Comment by Yauxo** [comment]
Pretty sure you need to be "in front" of this thing for the second one.
![boiler](http://puu.sh/lNNLG/2577887113.jpg)

Same thing if youre "in front" of the pipe that leads outwards and turn into another view.
![pipe](http://puu.sh/lNNBb/8181d8f561.jpg)
(pipe on the right)

**Comment by renaudbedard** [comment]
Fixed!
