### ISSUE TITLE
Switching from Fullscreen to Windowed ignores Borderless setting

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#43]
It seems that the Borderless setting is ignored while switching to Fullscreen to Windowed mode.

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/Fullscreen2WindowedBorderless.png

Also, maybe we could save a line by removing the Bordeless setting, and adding "Windowed Bordeless" in the "Screen Mode" list. :3

**Comment by flibitijibibo** [comment]
This should be resolved in the next push - IsBorderlessEXT was being called before ApplyChanges, which won't work in the situation you described.
