### ISSUE TITLE
Boiler Room Golden Map Issue

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#46]
![](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/BoilerRoomMap.png)

The room is not gold, while everything has been found. =/

**Comment by renaudbedard** [comment]
Oh balls... this may be something I introduced yesterday when fixing the sound bug (#9). I'll take a look.

**Comment by Gimlao** [comment]
Actually, it's not related to the "Achievement Unlocked" anticube.

**Comment by Gimlao** [comment]
It seems that it has not been fixed. :3

**Comment by renaudbedard** [comment]
Fixed now!
