### ISSUE TITLE
Crash while starting a new game

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#47]
Started a new game, then, while going out of Gomez room, this happened : 
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/wut.png (infinite loading)

Debug Log : http://pastebin.com/3fPMWsth

**Comment by renaudbedard** [comment]
Does this happen every time you try to start a new game, or randomly?

**Comment by Gimlao** [comment]
Only once, for now...

**Comment by renaudbedard** [comment]
I think I just fixed this particular problem, but it's gonna be hard to reproduce and hard to test. Fingers crossed!
