### ISSUE TITLE
Camera glitch during rotations in some places

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#48]
Right at the moment I pressed Q : 

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/camera_glitch1.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/camera_glitch2.png

=/

**Comment by renaudbedard** [comment]
D'oh!! Introduced by me fixing #24 in a careless way... will address right now. This is gonna break everywhere O_O

**Comment by Gimlao** [comment]
Yeah, it will center the camera everywhere now, even where its vertical position should be fixed. ^^;

**Comment by renaudbedard** [comment]
Fixed, patch should be live right now for Windows. Sorry about that :o

**Comment by Gyoo** [comment]
It seems that somthing similar is happening during the 64 Cubes ending : when you rotate the camera, it translates to the middle of the room, then rotates, and focuses back on Gomez. Because of that, Gomez can be off screen for a short while.

**Comment by renaudbedard** [comment]
Reopening for issue mentioned above.

**Comment by renaudbedard** [comment]
Fixed how the camera alignment works in the zoom-out sequence, I think it works better this way.
