### ISSUE TITLE
Gomez keeps sleep progress across savegames

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#50]
Start a new game and just while Gomez wakes up / stands up, start another game (by f.e. resetting the savegame). Gomez is already awake and listening to user input during the zoom in intro.

Alternatively, pausing and starting a new game while Gomez is still asleep shows that the animation still continues on where it was when pausing.

Fun side-effect: Going through the door produces following screenshot, which is quite similar to the 0% trick: ![bildschirmfoto von 2015-12-11 21-08-00](https://cloud.githubusercontent.com/assets/1200380/11754387/4972d906-a04b-11e5-89dd-bf3a117dc310.png)

**Comment by renaudbedard** [comment]
Noted, thanks!
(siiiiiiiiigh this game's horrible state management)

**Comment by renaudbedard** [comment]
Should be fixed now!
