### ISSUE TITLE
Disabled menu text has shadow during transition

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#51]
During the menu transition, disabled options have got their shadow enabled. Once transitioning in the menu, the shadow vanishes.

I don't know if it's caused by FEZMod's recent menu mods or any other FEZMod hack.

Growing menu, shadow enabled:
![frame 0](https://cloud.githubusercontent.com/assets/1200380/11761833/6cc2f1de-a0d2-11e5-8fe2-1f23dd597ce0.png)
Focusing on item and everything after that, shadow disabled:
![frame 1](https://cloud.githubusercontent.com/assets/1200380/11761828/49acdf98-a0d2-11e5-9e47-c5e9d4bfdcd5.png)

EDIT: Doesn't happen with the leaderboard / achievement options in the main menu.

**Comment by renaudbedard** [comment]
Haha dude, that's a really teeny tiny bug. I'll disregard since there's more pressing issues.

**Comment by renaudbedard** [comment]
Not to discourage you to submit bugs, I really appreciate it! But in the end this is the comestickest of cosmetic issues.

**Comment by 0x0ade** [comment]
Heh, when I was about to submit this, I sat for 15 minutes at the "new issue" screen, asking myself if it's critical enough and decided for "well, a bug is a bug".

I'll keep that in mind when submitting tiny bugs.
