### ISSUE TITLE
Geezer doesn't walk toward the mailbox

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#52]
Steps to reproduce: Start new game.

http://imgur.com/2CVCCd1
http://imgur.com/Tmdp1I5

Looks like he's trying to walk the wrong direction - he starts out facing left (correct), but then when his feet start moving he faces right (incorrect).

**Comment by renaudbedard** [comment]
Gah! Broken when fixing #28. Look like I forgot to test one NPC... I'll look into it.

**Comment by renaudbedard** [comment]
Fixed!
