### ISSUE TITLE
Polytron logo not displaying correctly

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#54]
Not exactly sure what caused this to occur.

On "reset" after Tetrahedron dialogue: ![image](https://cloud.githubusercontent.com/assets/16111792/11762741/b2f0d87c-a0b6-11e5-909d-d4e243899645.png)

On game start: ![image](https://cloud.githubusercontent.com/assets/16111792/11762721/36982eec-a0b6-11e5-8abd-e58b39d3ec68.png)

**Comment by renaudbedard** [comment]
Which resolution are you playing at?

**Comment by MistahKurtz** [comment]
2560x1440

**Comment by flibitijibibo** [comment]
I think this has to do with the view scale again, will look at it this week.

**Comment by flibitijibibo** [comment]
I'm actually having trouble reproducing this... windowed mode and even supersampled fullscreen (my display is only 1920x1200) seem to place the logo and text in the right place at that resolution. Once we do the next update check this one more time to see if it occurs. Might have just been a weird one-off, dunno.

**Comment by MistahKurtz** [comment]
Weird--it happens to me each time I launch the game at that resolution.

**Comment by flibitijibibo** [comment]
I doubt that this is the case, but with the latest FNA and SDL2 libs this _might_ have gotten fixed on Windows. When Renaud does the next update, check this out again. Worst case, we might have to do some printf debugging...

**Comment by renaudbedard** [comment]
99% sure I've fixed this in the latest update.
