### ISSUE TITLE
Falling off cliff after exiting room

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#55]
When exiting from that door, gomez will often fall off the ledge and into the water without any player input.

If dot is queued to give a speech, such as when you collect 16 cubes, and you fall of the ledge as you exit from that door, the game will soft lock. This could be related to the earlier soft lock bug with dot's speeches and landing on a ledge. 

(side note) I have had similar soft locks from collecting a red cube and exiting a room before dot can begin her "I don't know what that is." speech.

![2](https://cloud.githubusercontent.com/assets/16115136/11767182/7d482144-a16a-11e5-823d-700f1ca5b672.png)

**Comment by renaudbedard** [comment]
Fixed! (you should no longer fall in the water in that spawn point)
