### ISSUE TITLE
Graphical glitches when turning off hardware instancing

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#56]
This one speaks for itself.

(side note) Turning the hardware instancing back on mid game causes the game to crash for me shortly after visiting a new zone.

![1](https://cloud.githubusercontent.com/assets/16115136/11767195/55c4bce4-a16b-11e5-8150-a2e507459b6f.png)

**Comment by flibitijibibo** [comment]
Would this happen to be an Intel or AMD graphics chipset?

**Comment by Thejuikuen** [comment]
Intel

**Comment by flibitijibibo** [comment]
Mm, very well. I may have to chalk this up to the driver then, as I imagine it's not having a good time using one set of buffer object handles for wildly different shader/ARB_instanced_arrays combinations.

It sounds like either one will work as long as you stick to one for program runtime, so I'd stick to that for Intel hardware. (Maybe Mesa handles this better than the Windows drivers...?)

**Comment by renaudbedard** [comment]
I'll try to reproduce locally first, I haven't tried toggling the setting in a while. (though I remember it working when I first made it)

**Comment by renaudbedard** [comment]
Found & fixed, thanks!
