### ISSUE TITLE
Water reflection disappearing 

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#59]
![8](https://cloud.githubusercontent.com/assets/16115136/11767425/b7722920-a172-11e5-8478-af7cbd97b3a3.png)

When dropping into the water the reflection becomes 

![9](https://cloud.githubusercontent.com/assets/16115136/11767429/c2996246-a172-11e5-9659-b78caa7ddf45.png)

The reflection will return to normal if you stop moving for a few seconds, but when you move it instantly disappears again.

This works in many areas with this kind of water reflection. 

(ps: that room is super creepy)

**Comment by Gimlao** [comment]
This may be linked.

Here, the reflection is fine : 
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/water_reflection1.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/water_reflection4.png

But here, it looks weird : 
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/water_reflection2.png
https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/water_reflection3.png

**Comment by flibitijibibo** [comment]
We actually broke and fixed this at one point during 1.12 development, but I guess it's back... if I remember correctly it's game logic and not rendering logic, so Renaud may have to be the one to check this out.

**Comment by renaudbedard** [comment]
Fixed! I was not setting a blending mode so it just inherited whatever, which made it break randomly.
