### ISSUE TITLE
Non working PS3 controller

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#6]
PlayStation icons are shown when plugging the PS3 controllers, but nothing happens when pressing buttons.

Don't know if it's a Win10 only issue.

**Comment by renaudbedard** [comment]
I do know that it's an issue with Windows drivers on Windows 10, however I don't know if it was working on Win 7 or 8.1. Can anyone else give it a shot?

**Comment by flibitijibibo** [comment]
Apparently DS4Windows is something that fixes this, but I think it also forcibly sends an XInput signal with it:

http://steamcommunity.com/groups/frameratepolice/discussions/0/535151589883097165/?tscn=1449855291#c487876568226623380

There's even light bar support in there... I wonder if SetLightBarEXT could make use of that.

**Comment by flibitijibibo** [comment]
Is this still a problem with the latest Win10? SDL's side is fixed with 2.0.4, so it's down to the driver now.

**Comment by renaudbedard** [comment]
Can't get it to work on mine still, same issue as above. DS4Windows also does not work with Sixaxis (on my end, again).
I'll close as "won't fix".
