### ISSUE TITLE
Infinite fall in Zu Code Loop

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#62]
For some reason, the "falling death animation" has a chance to not happen here : 

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/FEZ%2015_12_2015%2015_33_09.mp4

I was looking at my notes (► L ► Jump R ▼ Jump ▲) while entering the inputs.
This is not the first time I manage to do that. x)

**Comment by renaudbedard** [comment]
Fixed, thanks!
