### ISSUE TITLE
One of the explosive blocks can reappear

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#63]
When returning to that room, after destroying the explosive blocks, one of them will reappear : 

![](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/reappearing_destroyed_block.png)

We can't walk on it, and Gomez will fall through it.

**Comment by Gyoo** [comment]
Talking about explosive blocks, it is possible to complete one part of Mine_wrap with some explosive blocks not broken : http://i.imgur.com/6nnLk0v.png

**Comment by renaudbedard** [comment]
Fixed the original bug, Gyoo's is another (level design) bug that I won't fix.
Thanks!
