### ISSUE TITLE
Portal visual glitch

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#64]
Look what happened here : 

https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/FEZ%2015_12_2015%2016_10_47.mp4

**Comment by renaudbedard** [comment]
Looks like a freak occurence, I tried exactly what's in the video and couldn't get it to happen. Nothing in the code that would suggest this could happen either. Let me know if you have some special way of making it happen!

**Comment by flibitijibibo** [comment]
Closing due to old age, let us know if this shows up again...
