### ISSUE TITLE
Water_Wheel : Water level is inconsistent

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#66]
Okay, this is a bit of a tough one to explain.

In the Water Wheel room, the water level raises in a weird fashion. By that I mean it doesn't seem to raise or lower by the height of one block, which can lead to bizarre results.

When you enter the room for the first time and turn the wheel Left 2 or 3 times, it is possible to enter the bottom door while being in the water as shown here : http://i.imgur.com/ELdFtz1.png

Then, when you leave the room, the water is magically lowered down ! http://i.imgur.com/G4quHaV.png

I don't know yet if it affects other parts of the game where the water needs to be lowered down. I assume not since the height should be the same everywhere and it should be a single variable for all the water heights, but who knows...

**Comment by Gyoo** [comment]
Ok, this is actually glitchier that I thought and the water level outside isn't affected by this unexpected water lowering.

Here's a video to show the behaviour : https://www.youtube.com/watch?v=WrULRLkDZJM

**Comment by flibitijibibo** [comment]
We should probably fix the water level consistency, then we should be able to sidestep this particular problem. I think the accidental water level changes are caused by some code to prevent drowning upon entering a room, but if we fix the global water level function then this can be ignored.

That said, I'm looking at the function and I'm a bit scared to touch it... Renaud might have to do this as there are lots of magic numbers involved in the process.

**Comment by renaudbedard** [comment]
Fixed! (sorta)

The initial bug report of the water adjusting under Gomez's feet remains, that's a safety feature that I don't feel comfortable removing. HOWEVER, once the water level adjusts, it remains adjusted globally, so the water lowers everywhere; not just in the level where Gomez would've drowned. So it does feel more consistent.
This doesn't affect lava or sewage, just water.

The main issue is that water pumping can be stopped at arbitrary times and does not clamp to triles or any kind of unit. This causes some rare gameplay issues but it's not a trivial thing to change, so I think the fix as is it is good enough.
