### ISSUE TITLE
Glitched texture on top of Metatron

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#67]
This is cosmetic, but here's the process :
1) Fly cheat to go over the monolith in the Zu_Zuish room
2) Activate 3D vision
3) ?
4) Profit
https://www.gfycat.com/AfraidHonestAuk

**Comment by renaudbedard** [comment]
Hmmm yeah... I'll ignore the floor/ceiling z-fighting issues in first person view because there are a BUNCH. This one is especially harmless.
