### ISSUE TITLE
Invisible block in Quantum room

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#68]
http://i.imgur.com/LMlvBcj.png

Nothing more to say I guess. Also makes a weird display glitch when you watch it from the side : http://i.imgur.com/fMNa6Wt.png

**Comment by flibitijibibo** [comment]
Well, what do you know... I think this is just a single trile in the level data that can be removed. @renaudbedard?

**Comment by renaudbedard** [comment]
Fixed! Removed the offending trile.
