### ISSUE TITLE
[Nuzu School] Camera zoom in / out

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#69]
[» Video Here «](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/FEZ%2017_12_2015%2021_57_07.mp4)

Right after using « ▲ ◄ R Jump L ► Jump ▼ », the camera will zoom out : 

![](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/NuzuSchool1.png)

Rotating / Getting the anticube will do some zoom in / out : 

![](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/NuzuSchool2.png)

I always wondered if it was a bug.

**Comment by renaudbedard** [comment]
Yeah I'd say that's a bug. Low priority but I'll take a look!

**Comment by Gimlao** [comment]
After that, the camera will always be zoomed out in that room.

**Comment by renaudbedard** [comment]
Fixed! The same volume was used to detect the code and to focus the camera, and volumes with code detection scripts attached disable themselves when the code is entered, which also killed the camera focusing. I separated into 2 volumes and it's all good. :)

**Comment by neizod** [comment]
Can I re-open this issue again? Since it's coming back on the Nintendo Switch version 😢
