### ISSUE TITLE
Crash on Fedora Linux x64 related to multithreading

### ISSUE THREAD

**Issue by luisfcorreia** [renaudbedard/fez-1.12-issues#7]
Fedora Linux 22 x86_64 - Steam beta build fna-unstable

Crashes are mostly random, most appear when rotating view and/or entering/leaving locations.

Debug log is (hopefully) attached

[Debug Log.txt](https://github.com/renaudbedard/fez-1.12-issues/files/49193/Debug.Log.txt)

**Comment by luisfcorreia** [comment]
New crash, different debug message:

(23:40:59.242) [Unhandled Exception] ERROR : System.NullReferenceException: Object reference not set to an instance of an object
  at FezEngine.Tools.Worker`1[System.Collections.Generic.Dictionary`2[Microsoft.Xna.Framework.Point,FezEngine.Services.Limit]].Act () [0x00000] in <filename unknown>:0 
  at FezEngine.Tools.PersistentThread.DoActualWork () [0x00000] in <filename unknown>:0 
  at Common.Logger.Try (System.Action action) [0x00000] in <filename unknown>:0

**Comment by renaudbedard** [comment]
If you manage to test on other platforms, let me know if they occur on OS X/Windows. This is the first I hear about them.

Also : can you try toggling to Singlethreaded mode from the in-game options menu and see if that fixes it?

**Comment by flibitijibibo** [comment]
These both look to be issues fixed by singlethreaded mode, flibitQA found the same issues.

**Comment by luisfcorreia** [comment]
confirmed, switching to singlethread fixes it and makes the game playable

**Comment by renaudbedard** [comment]
Wait, do we know why multithreaded loading makes it fail? Seems like a problem if the game is multithreaded by default.

**Comment by luisfcorreia** [comment]
I can test other builds for threading issues if need be

**Comment by renaudbedard** [comment]
I'll reopen this one so I don't forget about it. I'm not super thrilled about the game having to run singlethreaded on Linux,... but if we need to, I'll enable it by default.

**Comment by flibitijibibo** [comment]
I just hit this too - the null reference is the thread's task. This should only be null once we've disposed the worker, so our problem is that we're calling workers after they've been disposed. Some more checks should properly resolve this.

**Comment by luisfcorreia** [comment]
With latest (as of today) build, it no longer freezes when entering/exiting rooms or levels.

Will test it out a bit further but I guess it seems fixed.

**Comment by renaudbedard** [comment]
Just saw the above comment, good enough for me!
