### ISSUE TITLE
Double space in some texts

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#70]
"64 [double space here] cubes"
![](https://dl.dropboxusercontent.com/u/12308005/Jeux/Fez/screens/64cubes.png)

There may be other ones, I don't remember, for now. :3

**Comment by renaudbedard** [comment]
Fixed all instances of that bug, it was a weird space character (maybe an em-space or a non-breaking space) that was used by localization guys around numbers...
