### ISSUE TITLE
Trapped in save menu when going back from main menu

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#73]
- Start game
- Pick a save
- During the transition: Hit escape

Alternatively:
- Go to options menu
- Hit escape
- Hit escape a second time during the transition

Selecting a save is impossible. One can only exit the game from there (ESC or ALT+F4).

**Comment by flibitijibibo** [comment]
Does this still happen? I can't reproduce this myself.

**Comment by 0x0ade** [comment]
It's fixed. (I should've tested it more often...)
