### ISSUE TITLE
Rotation teleport

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#76]
This is kind of a known glitch. 

You press rotate a frame or two before entering a door and it will teleport you to the last door you exited. This seems to only work once per normal entrance on a map.

https://gfycat.com/DistantReflectingBandicoot

**Comment by flibitijibibo** [comment]
I'm pretty sure I got this one... how I dealt with this was by checking player input before validating the door entry. If rotation was pressed on that frame then we skip the entry.

This sounds weird when we know that the button is pressed _before_ door entry, but the odds of someone pressing rotate, then immediately unpressing the next frame at the exact same time as pressing enter is TAS levels of crazy. It's not quite impossible, but all my attempts to do this have failed.

If someone with better timing than me can hit this, let me know... I feel like there should be a better way of knowing when not to allow door entry, but I can't quite get to it.

Anyway, this patch should be in the next update.

**Comment by Gyoo** [comment]
> but the odds of someone pressing rotate, then immediately unpressing the next frame at the exact same time as pressing enter is TAS levels of crazy. It's not quite impossible, but all my attempts to do this have failed.

Well believe it or not but I remember it happened once when I was grinding runs a long time ago and I was like dafuq just happened (and I reset)
