### ISSUE TITLE
Clipping with various objects

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#77]
Its possible to clip through walls using certain world objects and rotating the screen. 

https://gfycat.com/RegalHandmadeDungbeetle
https://gfycat.com/ObviousTanGalapagossealion

This also has a weird side effect of making you immortal on respawn. 

https://gfycat.com/PreciousSandyGoshawk

**Comment by Gyoo** [comment]
RIP Black hole backup strat

**Comment by Thejuikuen** [comment]
Just gonna have to reset. It's early in the run now.

**Comment by renaudbedard** [comment]
Fixed in all reported instances! Thanks for waiting ^_^
