### ISSUE TITLE
Clipping through walls with open doorways

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#78]
It's possible to pass through certain doors just by pressing up without having to rotate platforms.

https://gfycat.com/SatisfiedGlisteningEmu
https://gfycat.com/AgreeableAromaticAstrangiacoral

**Comment by renaudbedard** [comment]
Fixed by disallowing the "enter tunnel" action to be triggered when Gomez is in silhouette "background" mode. Thanks!
