### ISSUE TITLE
Chest-Anticube-Duplication

### ISSUE THREAD

**Issue by Yauxo** [renaudbedard/fez-1.12-issues#80]
More dupes.
https://www.youtube.com/watch?v=7op8L7wq8ks 

Basically, you can spawn two cubes (in this case, ach and qr) while opening a chest and collect them really quick (spam a). This adds one cube to your count, but doesnt set any of the cubes as collected. Video is from 1.11, tested in 1.12

**Comment by flibitijibibo** [comment]
This one turned out to be as simple as ignoring code input when the cutscene is running. Should be fixed in the next update!
