### ISSUE TITLE
Wrong position when switching side after dying while crossing a spinning platform during fall

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#82]
Sorry for the long title, I didn't find a better way to express it. Basically, here is what has been found by someone and posted on speedrun.com's forums : https://www.youtube.com/watch?v=JZH-HLstuuU

I assume he did it on 1.11 but I was able to reproduce the exact same thing with the exact same steps on my 1.12 test build

**Comment by vrubleg** [comment]
Wrong position when rotating while Gomez stays at the edge of some platforms. Very easy to reproduce:
https://youtu.be/o8RoWWX4k6Y?t=13s

Not significant, just for information.

**Comment by renaudbedard** [comment]
Finally fixed! Just a respawn bug, the overlap data wasn't being cleared in time and in some cases this can cause the player hugging walls that don't correspond to where he is.
