### ISSUE TITLE
Game crashing when changing controls 

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#83]
This may be a glitch in the debug version only, but when changing the mapping for the controller, if you have two duplicate buttons, the game will crash.

**Comment by flibitijibibo** [comment]
Guess I'll have to do a dupe check, or swap buttons, or something... in my own testing it didn't crash, but I wonder if it depends on the button combination.

**Comment by flibitijibibo** [comment]
I'll try to fix this on Monday. I really just need to add swapping logic and that should be it, but you know how this can go...

**Comment by flibitijibibo** [comment]
This will be fixed in the next update.
