### ISSUE TITLE
Strange filter applied in CMYKave

### ISSUE THREAD

**Issue by MistahKurtz** [renaudbedard/fez-1.12-issues#84]
When I entered the tuning fork room in the CMYKave, in addition to the "ring of light" filter, there were other images in the shape of Gomez models. You should really just watch it. This is more of an FYI than anything else, since I don't know what might have caused this and it's only happened once.

http://www.twitch.tv/mistahkurtz7/v/34807726

![image](https://cloud.githubusercontent.com/assets/16111792/12227077/c637d7c2-b7eb-11e5-8eec-a95b7abad054.png)

**Comment by flibitijibibo** [comment]
This may be a consequence of uninitialized texture memory but that's entirely a guess; could be misuse of a valid texture too. Will tag this under generic rendering issues, hoping it's not FNA...

**Comment by flibitijibibo** [comment]
Closing due to old age, let us know if this happens again (and what might have been different when it happened).
