### ISSUE TITLE
Showing map icon on save slots

### ISSUE THREAD

**Issue by Gyoo** [renaudbedard/fez-1.12-issues#86]
Second feature request related to save slots.

On the interface, you have currently only the percentage of completion, but you don't know where you are. It would be handy to have the map image of the room you're in appearing somewhere next to the currently selected save. I don't know how big of a change it'd be, but combined with the previous request (adding more save slots) it'd be the perfect training station ^^

If this is unclear, I'll make a picture of what I mean when I have more time.

**Comment by flibitijibibo** [comment]
We'll give this a go in the next update, may involve prettification like the speedrun mode:

https://twitter.com/flibitijibibo/status/725170453699002370

**Comment by flibitijibibo** [comment]
Fixed all the weirdness in the prototype, this should be happily working in the next update.
