### ISSUE TITLE
Graphical glitch during fez delivery

### ISSUE THREAD

**Issue by ghost** [renaudbedard/fez-1.12-issues#88]
https://www.dropbox.com/s/ik68lxqkm9q0tlv/224760_2016-01-11_00003.png?dl=0

The lines stayed after the initial turning. They disappeared again a while later, once I was asked to turn the world myself. The lines were entirely static.

System info: https://gist.github.com/soeb/911716d900736035c2b1

**Comment by flibitijibibo** [comment]
I think this is related to the other issues WRT backbuffer writing...

**Comment by flibitijibibo** [comment]
Going over the steps to repro this might be a rendering logic issue rather than a GL issue. Dunno how the lines work though.

**Comment by flibitijibibo** [comment]
Closing due to old age - if this happens again with new builds, see if there was any specific process needed to make it happen.
