### ISSUE TITLE
Graphical glitch when opening a map

### ISSUE THREAD

**Issue by ghost** [renaudbedard/fez-1.12-issues#89]
https://www.dropbox.com/s/4725bofhq2p4xaz/224760_2016-01-11_00004.png?dl=0

This happened every time on my Intel/Linux laptop. Directly after opening the map things appear fine, but after any movement, what's visible in the screenshot appears.

System info: https://gist.github.com/soeb/5a32183b326f794b4476

EDIT: For further context, this happened with any of the graphical features disabled/enabled in any combination.

**Comment by flibitijibibo** [comment]
Use a fullscreen mode different from the desktop-native resolution. I think this is the same issue affecting my SteamOS devkit; we can't write to the backbuffer for some reason.

**Comment by flibitijibibo** [comment]
This might end up being a WONTFIX if Intel can't get it together... I think this _still_ happens on my devkit when it worked fine with Alchemist.

**Comment by ghost** [comment]
Sorry, should have mentioned this earlier - this was introduced with 1.12, running on the MonoGame-SDL2 branch I never see it.

Also, this is not exclusive to fullscreen, same happens in non-native resolutions and windowed.

Any other data I could provide?

**Comment by flibitijibibo** [comment]
This might be something we have to look at with apitrace. If you can get a trace, see if there are specific calls where weird alpha flickering is apparent in the output framebuffer. The GL state (including current state and preceding calls) along with the active shader might tell us what could be at fault.

**Comment by flibitijibibo** [comment]
I should point out for this issue that FEZ is not the only game affected... basically every title is like this on the devkit, even simple ones like Blueberry Garden. For whatever reason the trigger is totally random, but the most common one for me is toggling VSync (definitely makes Blueberry go nuts, not sure about others).

**Comment by flibitijibibo** [comment]
This has been fixed by the dumbest hardware fix I've ever written.
