### ISSUE TITLE
Boiler Room - Anticube Music x2

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#9]
It looks like the anticube music is played twice, creating a reverb effect, when getting that anticube.

**Comment by MistahKurtz** [comment]
If it's what I'm thinking of, this existed in 1.11 as well. I always assumed it was an intended property of the room.

**Comment by renaudbedard** [comment]
That's a scripting error (it always behaved this way, but it's still wrong...)
Also fixed the camera unconstrain when you resolve the puzzle, shouldn't have been the case.
