### ISSUE TITLE
Options that require a restart should be denoted with an asterisk

### ISSUE THREAD

**Issue by ghost** [renaudbedard/fez-1.12-issues#90]
The newly added settings that required a restart would probably look nicer (and also consistent!) if they had an asterisk next to them, just like the resolution options do.

Just a minor request though.

**Comment by Thejuikuen** [comment]
As far as I know the few that require it do?

**Comment by ghost** [comment]
Compare the two: https://www.dropbox.com/s/sig63zb9de1jm96/224760_2016-01-12_00001.png?dl=0
https://www.dropbox.com/s/yjkxp4lqt4lqby9/224760_2016-01-12_00002.png?dl=0

UI wise it's inconsistent - a note is present, but an asterisk noting that there is one is not.

**Comment by renaudbedard** [comment]
Yep, understood. Low on the priority list but a bug nonetheless :)

**Comment by flibitijibibo** [comment]
This has been implemented and will show up in the next update. Bonus: We only print an asterisk for actual changes - if the game is in singlethreaded mode, we only show an asterisk when the option is set to "off".
