### ISSUE TITLE
Navigating the leaderboards causes a crash

### ISSUE THREAD

**Issue by ghost** [renaudbedard/fez-1.12-issues#91]
When going first down the leaderboards, then back up, the game crashed. Here's the only output leading up to the crash:

 Arg_InsufficientSpace
 Inconsistency detected by ld.so: dl-close.c: 764: _dl_close: Assertion `map->l_init_called' failed!

Additionally, this was the only thing initally shown: https://www.dropbox.com/s/5ecjwq21cf9kuu5/224760_2016-01-11_00005.png?dl=0
Note also the UI issue with the 5th item on the list being invisible/overlapping.
I have 28 people on my Steam friends list that played the game, and the rest show up only once I scrolled down. When scrolling back up, the game crashed.

System info: https://gist.github.com/soeb/911716d900736035c2b1

**Comment by flibitijibibo** [comment]
This is only the friends mode, right? The other two modes are okay?

**Comment by flibitijibibo** [comment]
Fixed it - it was @johndrinkwater's name again. Good thing he's both on our friend lists, never would have found that...
