### ISSUE TITLE
Default key for first person view doesn't work

### ISSUE THREAD

**Issue by ghost** [renaudbedard/fez-1.12-issues#92]
The default is currently R Alt, however pressing it does not put me in first person view. If I set it to right alt (Alt Gr) myself, it appears as "none" in the settings and works.

This is with a UK layout on Linux.

Also, there's a funny menu mismatch, where when opening the menu, the fps view is at first split over 2 lines, before being corrected to stay on one.

**Comment by Thejuikuen** [comment]
It works for me. Also, the controller also works for me.

**Comment by flibitijibibo** [comment]
This is fixed in SDL2 upstream:

https://hg.libsdl.org/SDL/rev/25f67a2e77a0

For now, FNA_KEYBOARD_USE_SCANCODES will help.

**Comment by flibitijibibo** [comment]
I'm hoping 2.0.5 will be out sooner than later but if not I may just say "meh" and do a patched 2.0.4 build like I did with the GameControllerDB patch.

**Comment by flibitijibibo** [comment]
This has been fixed with the latest update to both FEZ and fnalibs.tar.bz2.
