### ISSUE TITLE
Corruption room has glitched blocks that get "stuck"

### ISSUE THREAD

**Issue by ghost** [renaudbedard/fez-1.12-issues#93]
https://www.dropbox.com/s/yoxn0kl11kxjjag/224760_2016-01-11_00006.png?dl=0

I believe this was present from the start of the Linux port (MG-SDL2 and so forth), but I never really got to this point back then, so I didn't find it until after release. I'm assuming this is an issue as I haven't observed the same behaviour in youtube videos. Using first person view always fixes this, turning usually also works towards removing the extra glitched cubes.

If it's unclear from the image - glitched cubes don't always disappear as Gomez moves around, which makes it rather hard to navigate the level at times.

I think there's another room where something like this happens, but I can't remember which one it was.

System info: https://gist.github.com/soeb/911716d900736035c2b1

**Comment by flibitijibibo** [comment]
I wonder if this has to do with #68... I wonder if this falls into the "weird culling" category. Either way there's a good chance this was on the 360 too. I assume this is still an issue?

**Comment by flibitijibibo** [comment]
Actually, ignore that other issue, I actually saw a culling oddity on startup too (in the debug mode, this wouldn't happen in real gameplay). Does this get fixed if you open/close the map in the latest build?

**Comment by renaudbedard** [comment]
Fixed, I introduced this recently when tweaking the "clean radius" of this effect, should be good now.
