### ISSUE TITLE
Stereoscopic 3D available to all save files

### ISSUE THREAD

**Issue by Thejuikuen** [renaudbedard/fez-1.12-issues#94]
Such a cool feature that mostly goes unused because once you unlock it, you probably already have everything in the game. 

The idea is it to make it so once you have unlocked it properly, it will also be available on other save files, including new ones. 

This will allow you to be able to play through the full game again with the stereoscopic 3D activated.

Potential issues I can see are; Once unlocked would that save file need to be preserved to keep the feature? Does it become available on other save files that have already been created or only new ones created after the fact? What happens if you delete the main save file, but have others with the feature unlocked? 

Alternate idea: What if completing the game with 64 cubes unlocked "new game ++" Where your cubes and collectibles are reset but you receive the 3d glasses from the hexahedron and can play through a completely fresh game with stereoscopic 3d and the other new game+ powerups? (flight and first person view)

**Comment by flibitijibibo** [comment]
I just wrote this in, should be available in the next update. The way it works is that we check on main menu init for save files that have 3D unlocked. As long as at least one save file has it, all save files will get the option. It should not affect the savedata in any way.
