### ISSUE TITLE
Crashing problems with Steam overlay on Windows

### ISSUE THREAD

**Issue by 0x0ade** [renaudbedard/fez-1.12-issues#97]
Disabling hardware instancing doesn't seem to help. This seems to be a Steam / driver bug that could affect more games, but FEZ is the first game I'm experiencing this with.

When starting the game, the game renders nothing / a black screen for a short time during the Polytron logo. I had a black screen during the Polytron logo with 1.11, but I always blamed the drivers. The stars in the FEZ logo don't render at all, except for one frame when initializing the save slot menu. After picking a slot and showing the main menu transition for a frame, the game completely gives up.

| Info | Value |
| --- | --- |
| GPU | ATI Radeon HD 4650 |
| Driver | 8.97.100-130424a-156445E-ATI |
| Catalyst | 13.4 |
| OpenGL [driver] | 3.3 [6.14.10.11672] |
| OS [NT] | Windows 8.1 [6.3.9600] |
| Steam | 1453778785 (Jan 25 2016, 17:54:47) |

I guess FNA can't call glDrawRangeElements. According to MSDN:

> Starting with the .NET Framework 4, AccessViolationException exceptions thrown by the common language runtime are not handled by the catch statement in a structured exception handler if the exception occurs outside of the memory reserved by the common language runtime.

This also explains why I had to go to the system event log for this error.

FEZ stack trace:

```
Anwendung: FEZ.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.AccessViolationException
   bei Microsoft.Xna.Framework.Graphics.OpenGLDevice.DrawIndexedPrimitives(Microsoft.Xna.Framework.Graphics.PrimitiveType, Int32, Int32, Int32, Int32, Int32, Microsoft.Xna.Framework.Graphics.IndexBuffer)
   bei Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(Microsoft.Xna.Framework.Graphics.PrimitiveType, Int32, Int32, Int32, Int32, Int32)
   bei FezEngine.Structure.Geometry.BufferedIndexedPrimitives`1[[FezEngine.Structure.Geometry.VertexFakePointSprite, FezEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Draw(FezEngine.Effects.BaseEffect)
   bei FezEngine.Structure.Group.Draw(FezEngine.Effects.BaseEffect)
   bei FezEngine.Structure.Mesh.Draw()
   bei FezGame.Components.StarField.Draw()
   bei FezGame.Components.Intro.Draw(Microsoft.Xna.Framework.GameTime)
   bei Microsoft.Xna.Framework.Game+<>c.<.cctor>b__104_0(Microsoft.Xna.Framework.IDrawable, Microsoft.Xna.Framework.GameTime)
   bei Microsoft.Xna.Framework.Game+SortingFilteringCollection`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEachFilteredItem[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Action`2<System.__Canon,System.__Canon>, System.__Canon)
   bei Microsoft.Xna.Framework.Game.Draw(Microsoft.Xna.Framework.GameTime)
   bei FezGame.Fez.Draw(Microsoft.Xna.Framework.GameTime)
   bei Microsoft.Xna.Framework.Game.Tick()
   bei Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Microsoft.Xna.Framework.Game)
   bei Microsoft.Xna.Framework.Game.Run()
   bei FezGame.Program.MainInternal()
   bei Common.Logger.Try(System.Action)
   bei FezGame.Program.Main(System.String[])

```

According to the FEZMod stack trace, which forces the language to be English, "The process was terminated due to an unhandled exception."

Application error, possible driver failure:

```
Name der fehlerhaften Anwendung: FEZ.exe, Version: 1.0.0.0, Zeitstempel: 0x56a76d48
Name des fehlerhaften Moduls: atioglxx.dll, Version: 6.14.10.11672, Zeitstempel: 0x51780940
Ausnahmecode: 0xc0000005
Fehleroffset: 0x001d18a0
ID des fehlerhaften Prozesses: 0x1980
Startzeit der fehlerhaften Anwendung: 0x01d1583937a30830
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Steam\steamapps\common\FEZ\FEZ.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\atioglxx.dll
Berichtskennung: 97590392-c42c-11e5-82b0-00248cb11e9b
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

Windows Error Reporting details:

```
Fehlerbucket 107914539630, Typ 1
Ereignisname: APPCRASH
Antwort: http://oca.microsoft.com/resredir.aspx?SID=1&iBucketTable=1&iBucket=107914539630&BucketHash=b41d46ba2a37dd04b7aef112416d09c4
CAB-Datei-ID: 0

Problemsignatur:
P1: FEZ.exe
P2: 1.0.0.0
P3: 56a6fe3c
P4: atioglxx.dll
P5: 6.14.10.11672
P6: 51780940
P7: c0000005
P8: 001d18a0
P9: 
P10: 

Angefügte Dateien:
C:\Users\mein\AppData\Local\Temp\WERB2D8.tmp.WERInternalMetadata.xml
C:\Users\mein\AppData\Local\Temp\WERB838.tmp.appcompat.txt

Diese Dateien befinden sich möglicherweise hier:
C:\Users\mein\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_FEZ.exe_dc75768fa434c396b52dda3adf580fc5b148533_64044748_17f3c0d2

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: e80d8393-c42c-11e5-82b0-00248cb11e9b
Berichtstatus: 1
Bucket mit Hash: b41d46ba2a37dd04b7aef112416d09c4
```

Disabling the FPS counter in Steam "fixes" this issue.

EDIT:

The stars still vanish permanently when opening the Steam overlay in either the logo or menu screens. The crash can be performed without the FPS counter by opening the Steam overlay during the transition from save selection menu to the main menu.

The new "fix" is to start FEZ outside of Steam.

**Comment by flibitijibibo** [comment]
Here's an odd idea: run in fullscreen mode with a resolution different from the desktop resolution. I've been getting some odd behavior on SteamOS when games write to the backbuffer, I wonder if this is related.

**Comment by flibitijibibo** [comment]
I believe this has been fixed by recent Steam client updates, as they were having a lot of trouble with this for other GL titles (Disgaea and friends). If not, that's Valve's problem first.
