### ISSUE TITLE
Crash when opening the inventory

### ISSUE THREAD

**Issue by Gimlao** [renaudbedard/fez-1.12-issues#98]
https://dl.dropboxusercontent.com/u/12308005/Jeux/FEZ/screens/FEZ%2031_01_2016%2002_30_21.mp4

> (00:59:28.440) [Version] INFORMATION : 1.12, Build Date : 2016-01-30 12:00:00 AM
> (00:59:29.079) [Instancing] INFORMATION : Hardware instancing is enabled
> (00:59:29.083) [SettingsManager] INFORMATION : Screen set to {{Width:1920 Height:1080 Format:Color}}
> (00:59:29.083) [SettingsManager] INFORMATION : Screen mode is : Windowed
> (00:59:29.083) [SettingsManager] INFORMATION : Backbuffer is 1280x720
> (00:59:29.084) [SettingsManager] INFORMATION : VSync is on
> (00:59:29.084) [SettingsManager] INFORMATION : Multisample count is 0
> (00:59:29.168) [Threading] INFORMATION : Multithreading is enabled
> (00:59:29.759) [Intro] INFORMATION : First draw done!
> (00:59:32.076) [StaticPreloader] INFORMATION : SharedContentManager preloaded.
> (00:59:33.919) [StaticPreloader] INFORMATION : Music library initialized.
> (00:59:33.949) [StaticPreloader] INFORMATION : Volume levels loaded.
> (00:59:34.016) [StaticPreloader] INFORMATION : Animations filled.
> (00:59:34.017) [StaticPreloader] INFORMATION : Text scroll pre-initialized.
> (00:59:34.017) [StaticPreloader] INFORMATION : World map pre-initialized.
> (00:59:34.018) [StaticPreloader] INFORMATION : Pause menu pre-initialized.
> (00:59:34.324) [Intro] INFORMATION : Preloading complete.
> (01:01:16.295) [Intro] INFORMATION : Level load complete.
> (01:01:21.125) [Intro] INFORMATION : Intro is done and game is go!
> (02:26:04.386) [Content] WARNING : Couldn't find asset in references : Background Planes\UNDER_PIPE_A

I don't know if opening the inventory, or pressing LB / RB (don't remember) in the inventory caused the crash.

**Comment by flibitijibibo** [comment]
Was this a crash or a freeze...? I would have expected a stack trace for a crash. If it was a freeze this might have been fixed by all the threading "stuff" we did a while back, but if not, see if you can get this to happen again. If we can't repro then I'll just mark this as a one-timer...

**Comment by renaudbedard** [comment]
If it's a hang, I've fixed a related issue yesterday. If you can't get it to trigger anymore I'll assume it as fixed. (it works here)
